### 使用 三段式查看 绩效

In [1]:
import pandas  as pd
import numpy as np
import pdb, os, datetime, itertools, time, hashlib
import pyprojroot, sys
from pyprojroot.criterion import has_file
sys.path.insert(0, str(pyprojroot.find_root(has_file("pyproject.toml"))))

from dotenv import load_dotenv
load_dotenv()

from lib.flp001 import *

/workspace/worker/pj/Chrono/genuis/mizar
/workspace/worker/pj/Chrono/genuis/mizar/config/contract.toml

In [2]:
method = 'ricso2'
task_id = '134001'
instruments = 'hcb'
period = 5
category='p'

In [3]:
draft_data_recent = load_data3(method=method, task_id=task_id, instruments=instruments, 
          period=period, category=category,filename='cohort_pro.csv')
draft_data_recent['types'] = 'recent'
draft_data_recent.sort_values(by=['ann_sharpe'],ascending=False)[['formula','ic_mean','ann_sharpe','calmar','pl_ratio']]

,formula,ic_mean,ann_sharpe,calmar,pl_ratio
1,"MRANK(120,MDIFF(5,SIGLOG2ABS('dv002_2_3_1')))",-0.0623,2.15,2.66,None
0,"SIGLOGABS(MMinDiff(60,'dv002_2_3_1'))",-0.0615,2.14,3.17,None
2,"MMinDiff(60,'dv002_2_3_1')",-0.0615,2.14,3.17,None

In [4]:
draft_data_train = load_data2(method=method, task_id=task_id, instruments=instruments, 
          period=period,filename='cohort_pro.csv')
draft_data_recent['types'] = 'train'
draft_data_train.sort_values(by=['ann_sharpe'],ascending=False)[['formula','ic_mean','ann_sharpe','calmar','pl_ratio']]

,formula,ic_mean,ann_sharpe,calmar,pl_ratio
0,"SIGLOGABS(MMinDiff(60,'dv002_2_3_1'))",-0.0713,2.26,2.27,None
2,"MMinDiff(60,'dv002_2_3_1')",-0.0713,2.26,2.27,None
1,"MRANK(120,MDIFF(5,SIGLOG2ABS('dv002_2_3_1')))",-0.0729,2.22,2.26,None

In [5]:
draft_data_train.loc[0]['plot']

'/workspace/worker/pj/Chrono/genuis/mizar/records/ricso2/hcb/rulex/134001/nxt1_ret_5h/20260401/10598969/comparison_plot.png'

In [6]:
draft_data = pd.concat([draft_data_train,draft_data_recent],axis=0).sort_values(by=['factor_id'])

In [7]:
to_html(draft_data[['factor_id','direction','formula','types','plot']])