In [1]:
import pandas  as pd
import numpy as np
import pdb, os, datetime, itertools, time, hashlib
import pyprojroot, sys
from pyprojroot.criterion import has_file
sys.path.insert(0, str(pyprojroot.find_root(has_file("pyproject.toml"))))
from dotenv import load_dotenv

load_dotenv()
from lib.flp001 import *

/workspace/worker/pj/Chrono/genuis/mizar
/workspace/worker/pj/Chrono/genuis/mizar/config/contract.toml

In [2]:
method = 'ricso2'
task_id = '159001'
session = '20260606'
period = 5
category = 1
left_instruments = 'pc'
right_instruments = 'yc'

In [3]:
results = fetch_data(method=method, task_id=task_id, instruments=left_instruments, 
          period=period, session=session, category=category)
results['name'] = results['name'].astype(int).astype(str)
results['ic_mean'] = pd.to_numeric(results['ic_mean'], errors='coerce')
results['total_ic'] = pd.to_numeric(results['total_ic'], errors='coerce')
results['abs_ic_mean'] = results['ic_mean'].abs()
results['abs_total_ic'] = results['total_ic'].abs()

/workspace/worker/pj/Chrono/genuis/mizar/records/ricso2/pc/rulex/159001/nxt1_ret_5h/20260606

In [4]:
left_results = results[results['instrument'] == left_instruments]
right_results = results[results['instrument'] == right_instruments]

In [5]:
left_results[['instrument','name', 'expression', 'avg_ret', 'total_ret', 
              'max_dd', 'calmar', 'win_rate', 'pl_ratio', 'ic_mean', 'icir',
              'sharpe', 'ann_sharpe','total_ic']].head()

Empty DataFrame
Columns: [instrument, name, expression, avg_ret, total_ret, max_dd, calmar, win_rate, pl_ratio, ic_mean, icir, sharpe, ann_sharpe, total_ic]
Index: []

In [6]:
right_results[['instrument','name', 'expression', 'avg_ret', 'total_ret', 
              'max_dd', 'calmar', 'win_rate', 'pl_ratio', 'ic_mean', 'icir',
              'sharpe', 'ann_sharpe','total_ic']].head()

Empty DataFrame
Columns: [instrument, name, expression, avg_ret, total_ret, max_dd, calmar, win_rate, pl_ratio, ic_mean, icir, sharpe, ann_sharpe, total_ic]
Index: []

In [7]:
### 初步筛选双品种保持一致

In [8]:
ic_mean = 0.03
total_ic = 0.015
ann_sharpe = 2
calmar = 1.5

In [9]:
left_results1 = left_results[(left_results['abs_ic_mean'] >= ic_mean) & (
    left_results['abs_total_ic'] >= total_ic
) & (
    left_results['ann_sharpe'] >= ann_sharpe
) & (
    left_results['calmar'] >= calmar
)]

left_results1.head()

Empty DataFrame
Columns: [name, expression, avg_ret, total_ret, sharpe, ann_sharpe, max_dd, calmar, win_rate, pl_ratio, ic_mean, icir, turnover, factor_ac, ret_ac, roll_win, resampling_win, holding_profit, total_ic, category, instrument, abs_ic_mean, abs_total_ic]
Index: []

[0 rows x 23 columns]

In [10]:
right_results1 = right_results[(right_results['abs_ic_mean'] >= ic_mean) & (
    right_results['abs_total_ic'] >= total_ic
) & (
    right_results['ann_sharpe'] >= ann_sharpe
) & (
    right_results['calmar'] >= calmar
)]

right_results1.head()

Empty DataFrame
Columns: [name, expression, avg_ret, total_ret, sharpe, ann_sharpe, max_dd, calmar, win_rate, pl_ratio, ic_mean, icir, turnover, factor_ac, ret_ac, roll_win, resampling_win, holding_profit, total_ic, category, instrument, abs_ic_mean, abs_total_ic]
Index: []

[0 rows x 23 columns]

In [11]:
# 关注的核心绩效指标
perf_cols = ['ann_sharpe', 'calmar', 'abs_ic_mean', 'abs_total_ic', 'max_dd', 'avg_ret', 'total_ic', 'ic_mean']

# 挑选需要的列参与合并
key_cols = ['name', 'expression']
merged_results = pd.merge(
    left_results1[key_cols + perf_cols],
    right_results1[key_cols + perf_cols],
    on=key_cols,
    how='inner',
    suffixes=('_{0}'.format(left_instruments), '_{0}'.format(right_instruments))
)

# 按照 [name, expression, ann_sharpe_hcb, ann_sharpe_rb, ...] 的顺序排布便于直接对比
display_cols = key_cols + [f"{col}_{suf}" for col in perf_cols for suf in [left_instruments, right_instruments]]
merged_results = merged_results[display_cols]

display(merged_results.sort_values(by=["ann_sharpe_{0}".format(left_instruments)]))

Empty DataFrame
Columns: [name, expression, ann_sharpe_pc, ann_sharpe_yc, calmar_pc, calmar_yc, abs_ic_mean_pc, abs_ic_mean_yc, abs_total_ic_pc, abs_total_ic_yc, max_dd_pc, max_dd_yc, avg_ret_pc, avg_ret_yc, total_ic_pc, total_ic_yc, ic_mean_pc, ic_mean_yc]
Index: []

In [12]:
import numpy as np

# 1. 指定判断方向所用的列（使用 left_instruments 即 hcb 的列）
total_ic_col = f'total_ic_{left_instruments}'  # 即 'total_ic_hcb'
ic_mean_col = f'ic_mean_{left_instruments}'    # 即 'ic_mean_hcb'

# 2. 计算方向字段：都为正为 1，都为负为 -1，不一致为 0
conditions = [
    (merged_results[total_ic_col] > 0) & (merged_results[ic_mean_col] > 0),
    (merged_results[total_ic_col] < 0) & (merged_results[ic_mean_col] < 0)
]
choices = [1, -1]
merged_results['direction'] = np.select(conditions, choices, default=0)

# 3. 构造 plot 路径（已修正多余的 '+'，并将 results['name'] 改为 merged_results['name']）
session_name = "/{0}".format(session) if category == 1 else "/d{0}".format(session)  
merged_results['plot'] = (
    base_path + '/' + str(method) + '/' + left_instruments \
    + '/rulex' + '/' + str(task_id) + f"/nxt1_ret_{period}h" \
    + session_name + '/plot/' + merged_results['name'].astype(str) + '.png'
)

# 4. 保留指定列并重命名，渲染可点击链接
merged_results = merged_results[['expression', 'plot', 'name', 'direction']].rename(
    columns={'name': 'factor_id', 'expression': 'formula'}
)
merged_results['plot'] = merged_results['plot'].apply(make_clickable)

#display(merged_results.)

In [13]:
to_html(merged_results)

In [14]:
merged_results

Empty DataFrame
Columns: [formula, plot, factor_id, direction]
Index: []

In [15]:
### 转成临时格式
merged_results1 = merged_results[['formula','direction']]
merged_results1['source'] = session
merged_results1['category'] = 'p'
merged_results1.head()

Empty DataFrame
Columns: [formula, direction, source, category]
Index: []

In [16]:
session_name = f'd{session}' if category == 2 else str(session)
file_path = Path(base_path) / method / left_instruments / 'rulex' / task_id / (f'nxt1_ret_{period}h')
file_path

PosixPath('/workspace/worker/pj/Chrono/genuis/mizar/records/ricso2/pc/rulex/159001/nxt1_ret_5h')

In [17]:
merged_results1.to_csv(os.path.join(file_path, "{0}_cohort.csv".format(session)),encoding='UTF-8')

In [18]:
merged_results1.shape

(0, 4)