In [1]:
import pandas  as pd
import numpy as np
import pdb, os, datetime, itertools, time, hashlib
import pyprojroot, sys
from pyprojroot.criterion import has_file
sys.path.insert(0, str(pyprojroot.find_root(has_file("pyproject.toml"))))
from dotenv import load_dotenv

load_dotenv()
from lib.flp001 import *

/workspace/worker/pj/Chrono/genuis/mizar
/workspace/worker/pj/Chrono/genuis/mizar/config/contract.toml

In [2]:
method = 'ricso2'
task_id = '159001'
period = 5
category = 1
left_instruments = 'pc'
right_instruments = 'yc'
filename = 'cohort.csv'

In [3]:
def filter(results, left_instruments, right_instruments, total_ic, ic_mean,
           ann_sharpe, calmar):
    results['name'] = results['name'].astype(int).astype(str)
    results['ic_mean'] = pd.to_numeric(results['ic_mean'], errors='coerce')
    results['total_ic'] = pd.to_numeric(results['total_ic'], errors='coerce')
    results['abs_ic_mean'] = results['ic_mean'].abs()
    results['abs_total_ic'] = results['total_ic'].abs()
    left_results = results[results['instrument'] == left_instruments]
    right_results = results[results['instrument'] == right_instruments]
    left_results1 = left_results[(left_results['abs_ic_mean'] >= ic_mean)
                                 & (left_results['abs_total_ic'] >= total_ic) &
                                 (left_results['ann_sharpe'] >= ann_sharpe) &
                                 (left_results['calmar'] >= calmar)]
    right_results1 = right_results[
        (right_results['abs_ic_mean'] >= ic_mean)
        & (right_results['abs_total_ic'] >= total_ic) &
        (right_results['ann_sharpe'] >= ann_sharpe) &
        (right_results['calmar'] >= calmar)]
    perf_cols = [
        'ann_sharpe', 'calmar', 'abs_ic_mean', 'abs_total_ic', 'max_dd',
        'avg_ret', 'total_ic', 'ic_mean'
    ]

    # 挑选需要的列参与合并
    key_cols = ['name', 'expression', 'direction', 'source']
    merged_results = pd.merge(left_results1[key_cols + perf_cols],
                              right_results1[key_cols + perf_cols],
                              on=key_cols,
                              how='inner',
                              suffixes=('_{0}'.format(left_instruments),
                                        '_{0}'.format(right_instruments)))
    return merged_results

In [4]:
ic_mean = 0.025
total_ic = 0.015
ann_sharpe = 1.15
calmar = 1.15

full_period_results = fetch_data4(method=method, task_id=task_id, instruments=left_instruments, 
                      windows='full_period',period=period, filename=filename,
                      category='annual')


full_period_results = filter(results=full_period_results, 
       left_instruments=left_instruments, 
       right_instruments=right_instruments, 
           total_ic=total_ic, 
           ic_mean=ic_mean, 
           ann_sharpe=ann_sharpe, 
           calmar=calmar)

In [5]:
full_period_results

,name,expression,direction,source,ann_sharpe_pc,calmar_pc,abs_ic_mean_pc,abs_total_ic_pc,max_dd_pc,avg_ret_pc,total_ic_pc,ic_mean_pc,ann_sharpe_yc,calmar_yc,abs_ic_mean_yc,abs_total_ic_yc,max_dd_yc,avg_ret_yc,total_ic_yc,ic_mean_yc
0,10034719,"MDIFF(90,MDIFF(90,MPERCENT(90,MQUANTILE(60,'oi...",1,20260325,2.70,3.20,0.0286,0.0204,-9.41,0.16,0.0204,0.0286,2.77,3.55,0.0286,0.0215,-6.71,0.13,0.0215,0.0286
1,10081862,"MDIFF(90,MDIFF(90,MDIFF(10,'oi039_2_3_1')))",1,20260325,2.33,2.65,0.0416,0.0179,-10.67,0.15,0.0179,0.0416,2.72,3.63,0.0428,0.0215,-7.11,0.14,0.0215,0.0428
2,10084584,"MDIFF(90,'oi039_2_3_1')",1,20260325,2.33,2.65,0.0416,0.0179,-10.67,0.15,0.0179,0.0416,2.72,3.63,0.0428,0.0215,-7.11,0.14,0.0215,0.0428
3,10154525,"MDIFF(90,MDIFF(10,MDIFF(90,'oi039_2_3_1')))",1,20260325,2.33,2.65,0.0416,0.0179,-10.67,0.15,0.0179,0.0416,2.72,3.63,0.0428,0.0215,-7.11,0.14,0.0215,0.0428
4,10254465,"MDIFF(10,MMinDiff(60,'oi039_2_3_1'))",1,20260325,2.19,2.44,0.0268,0.0171,-10.60,0.14,0.0171,0.0268,2.49,3.81,0.0279,0.0200,-6.03,0.13,0.0200,0.0279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,10920428,FRAC(FRAC('tc014_2_2_3_1')),-1,20260605,2.26,3.25,0.0394,0.0170,-8.27,0.14,-0.0170,-0.0394,2.51,5.15,0.0413,0.0197,-4.56,0.13,-0.0197,-0.0413
220,10929051,"MRANK(90,'tc009_2_1_2_3_1')",-1,20260605,2.50,3.52,0.0346,0.0191,-8.17,0.15,-0.0191,-0.0346,2.45,3.03,0.0339,0.0189,-6.97,0.12,-0.0189,-0.0339
221,10948254,"MPERCENT(90,MADiff(240,'tc005_2_2_3_1'))",-1,20260605,2.56,3.57,0.0343,0.0195,-8.41,0.16,-0.0195,-0.0343,2.44,3.03,0.0327,0.0188,-7.07,0.12,-0.0188,-0.0327
222,10975553,"MRes(30,MDPO(240,DELTA(60,'cj011_1_2_1')),'tc0...",-1,20260605,2.13,2.07,0.0402,0.0162,-12.17,0.13,-0.0162,-0.0402,2.43,3.02,0.0409,0.0191,-7.50,0.12,-0.0191,-0.0409
223,10997062,"MPERCENT(90,MCPS(60,MPERCENT(90,'tc014_2_2_3_1...",1,20260605,2.53,3.40,0.0300,0.0190,-8.52,0.16,0.0190,0.0300,2.72,3.43,0.0313,0.0210,-7.05,0.13,0.0210,0.0313

In [6]:
MIN_ABS_TOTAL_IC = 0.01
MIN_ABS_IC_MEAN = 0.025

# 五年中单品种需要满足的年度数量
MIN_POSITIVE_RET_YEARS = 4 # 对每个品种分别检查，五年中必须五年 total_ret > 0
MIN_VALID_IC_YEARS = 4 # 对每个品种分别检查，五年中必须五年同时满足 abs_total_ic 和 abs_ic_mean 阈值
MIN_SAME_IC_SIGN_YEARS = 4 # 对每个品种分别检查，五年的原始 total_ic 必须全部保持同一正负方向

# RB、HC 同时满足条件的年度数量
MIN_BOTH_RET_YEARS = 4 # 对每个因子检查，必须五年中每一年 RB 和 HC 都同时收益为正
MIN_BOTH_IC_YEARS = 4 # 对每个因子检查，必须五年中每一年 RB 和 HC 都同时达到绝对 IC 阈值

results = compare_years_factors(
    method=method,
    task_id=task_id,
    left_instruments=left_instruments,
    right_instruments=right_instruments,
    period=period,
    years=[2021, 2022, 2023, 2024, 2025],
    filename=filename,
    condition={
        'min_abs_total_ic': MIN_ABS_TOTAL_IC,
        'min_abs_ic_mean': MIN_ABS_IC_MEAN,
        'valid_ic_years': MIN_POSITIVE_RET_YEARS,
        'valid_ic_years': MIN_VALID_IC_YEARS,
        'same_ic_sign_years': MIN_SAME_IC_SIGN_YEARS,
        'both_ret_pass_years': MIN_BOTH_RET_YEARS,
        'both_ic_pass_years': MIN_BOTH_IC_YEARS
    },
    category='annual')

同一因子、品种和年度存在重复记录:
                expression instrument  year
MMaxDiff(90,'dv002_2_3_1')         pc  2021
MMaxDiff(90,'dv002_2_3_1')         yc  2021
      WMA(5,'oi004_2_3_1')         pc  2021
      WMA(5,'oi004_2_3_1')         yc  2021
  MADiff(90,'dv002_2_3_1')         pc  2021
  MADiff(90,'dv002_2_3_1')         yc  2021
MMaxDiff(90,'dv002_2_3_1')         pc  2021
MMaxDiff(90,'dv002_2_3_1')         yc  2021
      WMA(5,'oi004_2_3_1')         pc  2021
      WMA(5,'oi004_2_3_1')         yc  2021

In [7]:
results.keys()

dict_keys(['screening', 'passed', 'annual', 'asset_summary', 'paired_year', 'condition'])

In [8]:
passed_results = results['passed']

In [9]:
passed_results.head()

,expression,paired_year_count,both_ret_pass_years,both_ic_pass_years,left_mean_total_ret,right_mean_total_ret,left_mean_abs_total_ic,right_mean_abs_total_ic,weakest_mean_total_ret,weakest_mean_abs_total_ic,...,right_dominant_ic_sign,right_positive_ret_years,right_valid_ic_years,right_same_ic_sign_years,right_last_total_ret,right_last_abs_total_ic,right_last_abs_ic_mean,both_asset_pass,same_ic_direction,final_pass
0,"MMaxDiff(90,MADiff(90,'dv002_2_3_1'))",5,5,4,35.224,26.370,0.02174,0.02502,26.370,0.02174,...,-1,5,4,5,7.06,0.0294,0.0349,True,True,True
1,"MADiff(90,WMA(5,'dv002_2_3_1'))",5,5,4,29.504,20.656,0.01912,0.01920,20.656,0.01912,...,-1,5,4,5,5.03,0.0199,0.0382,True,True,True
2,"WMA(5,MADiff(90,'dv002_2_3_1'))",5,5,4,29.518,20.688,0.01910,0.01924,20.688,0.01910,...,-1,5,4,5,5.04,0.0199,0.0384,True,True,True
3,SIGLOG2ABS('db004_2_3_1'),5,5,4,22.648,18.302,0.01644,0.01772,18.302,0.01644,...,1,5,5,5,2.79,0.0117,0.0260,True,True,True
4,"MRes(120,WMA(5,'tn002_1_0'),MNPOSITIVE(120,'tv...",5,4,4,24.008,20.964,0.01894,0.01940,20.964,0.01894,...,1,5,4,5,4.40,0.0177,0.0480,True,True,True

In [10]:
### 满足全年和满足逐年做交集

In [11]:
new_expression = set(full_period_results['expression'].tolist()) & set(passed_results['expression'])

In [12]:
len(new_expression)

19

In [13]:
## 不看图时 可以先不用执行
results = merge_annual_factor_plots(method=method,
                              task_id=task_id,
                              instruments=left_instruments,
                              period=period,
                              expressions=new_expression,
                              years=[2021,2022,2023,2024,2025],
                              category='annual',
                              full_window='full_period',
                              columns=2,
                              cell_width=1600,
                              max_workers=4,
                              overwrite=True,
                              annual_root=None)
to_html(results)

In [14]:
results

,factor_id,formula,expression,plot,available_windows,missing_windows,complete,file_size_mb
0,10544376,"EMA(10,'tc008_1_2_0')","EMA(10,'tc008_1_2_0')",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.776
1,10330364,"WMA(5,MDIFF(15,'tv007_1_2_1'))","WMA(5,MDIFF(15,'tv007_1_2_1'))",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.801
2,10573642,"MMaxDiff(90,MADiff(90,'dv002_2_3_1'))","MMaxDiff(90,MADiff(90,'dv002_2_3_1'))",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.799
3,10749930,DIFF('tc018_2_3_1'),DIFF('tc018_2_3_1'),/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.835
4,10251469,"MADiff(90,WMA(5,'dv002_2_3_1'))","MADiff(90,WMA(5,'dv002_2_3_1'))",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.820
5,10748341,"MDIFF(90,'tc014_2_2_3_1')","MDIFF(90,'tc014_2_2_3_1')",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.824
6,10846629,SIGLOG2ABS('db004_2_3_1'),SIGLOG2ABS('db004_2_3_1'),/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.824
7,10375865,"ASIN(MCPS(120,MADecay(5,'dv002_2_3_1')))","ASIN(MCPS(120,MADecay(5,'dv002_2_3_1')))",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.788
8,10265008,"SIGLOGABS(WMA(5,'dv002_2_3_1'))","SIGLOGABS(WMA(5,'dv002_2_3_1'))",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.823
9,10660569,"MMinDiff(120,MMinDiff(120,MMinDiff(120,'ixy015...","MMinDiff(120,MMinDiff(120,MMinDiff(120,'ixy015...",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.829
10,10760084,"MRes(120,WMA(5,'tn002_1_0'),MNPOSITIVE(120,'tv...","MRes(120,WMA(5,'tn002_1_0'),MNPOSITIVE(120,'tv...",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.772
11,10257143,"MDIFF(240,'tc014_2_2_3_1')","MDIFF(240,'tc014_2_2_3_1')",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.825
12,10768534,"WMA(5,'dv002_2_3_1')","WMA(5,'dv002_2_3_1')",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.826
13,10860758,"MDIFF(240,MDIFF(240,MDIFF(240,MDIFF(240,MDIFF(...","MDIFF(240,MDIFF(240,MDIFF(240,MDIFF(240,MDIFF(...",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.833
14,10442478,"EMA(5,'tc004_1_1_2_0')","EMA(5,'tc004_1_1_2_0')",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.818
15,10845570,"MRes(120,WMA(5,'tn002_1_0'),MNPOSITIVE(120,EMA...","MRes(120,WMA(5,'tn002_1_0'),MNPOSITIVE(120,EMA...",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.776
16,10011577,"MDEMA(5,MDEMA(5,'oi004_1_2_1'))","MDEMA(5,MDEMA(5,'oi004_1_2_1'))",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.827
17,10954596,"MRes(120,WMA(5,'tn002_1_0'),EMA(15,MNPOSITIVE(...","MRes(120,WMA(5,'tn002_1_0'),EMA(15,MNPOSITIVE(...",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.781
18,10211238,"WMA(5,MADiff(90,'dv002_2_3_1'))","WMA(5,MADiff(90,'dv002_2_3_1'))",/workspace/worker/pj/Chrono/genuis/mizar/recor...,"full_period,year_2021,year_2022,year_2023,year...",,True,0.818

In [15]:
full_period_results

,name,expression,direction,source,ann_sharpe_pc,calmar_pc,abs_ic_mean_pc,abs_total_ic_pc,max_dd_pc,avg_ret_pc,total_ic_pc,ic_mean_pc,ann_sharpe_yc,calmar_yc,abs_ic_mean_yc,abs_total_ic_yc,max_dd_yc,avg_ret_yc,total_ic_yc,ic_mean_yc
0,10034719,"MDIFF(90,MDIFF(90,MPERCENT(90,MQUANTILE(60,'oi...",1,20260325,2.70,3.20,0.0286,0.0204,-9.41,0.16,0.0204,0.0286,2.77,3.55,0.0286,0.0215,-6.71,0.13,0.0215,0.0286
1,10081862,"MDIFF(90,MDIFF(90,MDIFF(10,'oi039_2_3_1')))",1,20260325,2.33,2.65,0.0416,0.0179,-10.67,0.15,0.0179,0.0416,2.72,3.63,0.0428,0.0215,-7.11,0.14,0.0215,0.0428
2,10084584,"MDIFF(90,'oi039_2_3_1')",1,20260325,2.33,2.65,0.0416,0.0179,-10.67,0.15,0.0179,0.0416,2.72,3.63,0.0428,0.0215,-7.11,0.14,0.0215,0.0428
3,10154525,"MDIFF(90,MDIFF(10,MDIFF(90,'oi039_2_3_1')))",1,20260325,2.33,2.65,0.0416,0.0179,-10.67,0.15,0.0179,0.0416,2.72,3.63,0.0428,0.0215,-7.11,0.14,0.0215,0.0428
4,10254465,"MDIFF(10,MMinDiff(60,'oi039_2_3_1'))",1,20260325,2.19,2.44,0.0268,0.0171,-10.60,0.14,0.0171,0.0268,2.49,3.81,0.0279,0.0200,-6.03,0.13,0.0200,0.0279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,10920428,FRAC(FRAC('tc014_2_2_3_1')),-1,20260605,2.26,3.25,0.0394,0.0170,-8.27,0.14,-0.0170,-0.0394,2.51,5.15,0.0413,0.0197,-4.56,0.13,-0.0197,-0.0413
220,10929051,"MRANK(90,'tc009_2_1_2_3_1')",-1,20260605,2.50,3.52,0.0346,0.0191,-8.17,0.15,-0.0191,-0.0346,2.45,3.03,0.0339,0.0189,-6.97,0.12,-0.0189,-0.0339
221,10948254,"MPERCENT(90,MADiff(240,'tc005_2_2_3_1'))",-1,20260605,2.56,3.57,0.0343,0.0195,-8.41,0.16,-0.0195,-0.0343,2.44,3.03,0.0327,0.0188,-7.07,0.12,-0.0188,-0.0327
222,10975553,"MRes(30,MDPO(240,DELTA(60,'cj011_1_2_1')),'tc0...",-1,20260605,2.13,2.07,0.0402,0.0162,-12.17,0.13,-0.0162,-0.0402,2.43,3.02,0.0409,0.0191,-7.50,0.12,-0.0191,-0.0409
223,10997062,"MPERCENT(90,MCPS(60,MPERCENT(90,'tc014_2_2_3_1...",1,20260605,2.53,3.40,0.0300,0.0190,-8.52,0.16,0.0190,0.0300,2.72,3.43,0.0313,0.0210,-7.05,0.13,0.0210,0.0313

In [16]:
factors_results = full_period_results[full_period_results['name'].isin(results.factor_id.tolist())]
factors_results.head()

,name,expression,direction,source,ann_sharpe_pc,calmar_pc,abs_ic_mean_pc,abs_total_ic_pc,max_dd_pc,avg_ret_pc,total_ic_pc,ic_mean_pc,ann_sharpe_yc,calmar_yc,abs_ic_mean_yc,abs_total_ic_yc,max_dd_yc,avg_ret_yc,total_ic_yc,ic_mean_yc
8,10330364,"WMA(5,MDIFF(15,'tv007_1_2_1'))",-1,20260325,2.37,2.36,0.0482,0.0190,-13.58,0.17,-0.0190,-0.0482,2.30,2.70,0.0427,0.0178,-8.23,0.12,-0.0178,-0.0427
17,10011577,"MDEMA(5,MDEMA(5,'oi004_1_2_1'))",-1,20260401,2.42,3.06,0.0365,0.0191,-9.80,0.16,-0.0191,-0.0365,2.35,3.36,0.0364,0.0185,-6.42,0.12,-0.0185,-0.0364
33,10211238,"WMA(5,MADiff(90,'dv002_2_3_1'))",-1,20260401,2.60,3.26,0.0339,0.0201,-10.13,0.17,-0.0201,-0.0339,2.56,4.08,0.0341,0.0198,-5.90,0.13,-0.0198,-0.0341
38,10251469,"MADiff(90,WMA(5,'dv002_2_3_1'))",-1,20260401,2.60,3.26,0.0338,0.0201,-10.13,0.17,-0.0201,-0.0338,2.56,4.09,0.0341,0.0198,-5.90,0.13,-0.0198,-0.0341
41,10265008,"SIGLOGABS(WMA(5,'dv002_2_3_1'))",-1,20260401,2.54,2.98,0.0393,0.0195,-10.72,0.17,-0.0195,-0.0393,2.40,4.09,0.0388,0.0187,-5.52,0.12,-0.0187,-0.0388

In [20]:
new_factors_results = factors_results[['expression','direction','source']].rename(
    columns={'expression':'formula'}).reset_index(drop=True)
new_factors_results['category'] = 'p'

In [24]:
### 加载已经使用的
import os
file_path = os.path.join(base_path, method, left_instruments, 'rulex', task_id,
                         "nxt1_ret_{0}h".format(period))
filename = os.path.join(file_path,"cohort_pro.csv")
current_factors = None
if os.path.exists(filename):
    current_factors = pd.read_csv(filename)

In [32]:
factors_res = [new_factors_results]
if current_factors is not None:
    factors_res.append(current_factors)

pd.concat(factors_res,axis=0).drop_duplicates(
    subset=['formula','direction']).to_csv(filename,encoding="UTF-8")

In [35]:
#full_period_results