In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# dt_path = '/workspace/worker/pj/Chrono/genuis/mizar/records/ricso2/vi/gentic/ic/118001/nxt1_ret_5h'
# file_path = Path(dt_path)
# res = []
# for feat_file in file_path.rglob('*.feather'):
#     dt1 = pd.read_feather(feat_file)
#     res.append(dt1)
    
# programes = pd.concat(res,axis=0)

In [3]:
# recent_data = pd.read_feather('/workspace/worker/pj/Chrono/genuis/mizar/records/ricso2/vi/basic/recent_data.feather')

In [4]:
# recent_data.columns

In [5]:
# programes.to_csv("temp_program.csv",encoding="UTF-8")

In [6]:
# pd.DataFrame(recent_data.columns[2:],columns=['featuers']).to_csv("feature_name.csv",encoding="UTF-8")

In [7]:
# programes

In [8]:
new_program = pd.read_csv("temp_program_feature_updated.csv",index_col=0).reset_index(drop=True)

In [9]:
new_program.drop_duplicates(subset=['formual'])

,name,method,gen,features,formual,final_fitness,raw_fitness,max_corr,penalty,alpha,update_time
0,ultron_1086340087875575,Gen,0,5bcf5da3c8961ef229414697d94243a6,"EMA(10,'tc008_5_15_0')",0.060898,0.060898,0,0,0,2026-05-05 06:42:31.442847
1,ultron_1009329337460366,Gen,0,2cebadf7c111bbc523ecdbeacc0ec837,"EMA(10,'cr042_1_3_1')",0.059792,0.059792,0,0,0,2026-05-06 17:32:49.504687
2,ultron_1007676351748701,Gen,0,da4f3fd65d83f73516bab8bfdeb95ec6,"EMA(5,MDIFF(10,'tv004_5_15_0'))",0.057222,0.057222,0,0,0,2026-05-03 18:57:12.711224
3,ultron_1064609757261927,Gen,0,2f94caf677335e1a736c799abeb02d0c,"EMA(5,'tc004_1_2_5_0')",0.057031,0.057031,0,0,0,2026-05-06 22:19:23.726364
4,ultron_1084360519926669,Hoist Mutation,1,302604235d9a5a2b1244e70fe9c6bf00,"SUBBED('tc009_1_2_5_5_1',MAPOSITIVE(240,'cr011...",0.056712,0.056712,0,0,0,2026-05-05 06:20:43.049190
...,...,...,...,...,...,...,...,...,...,...,...
18174,ultron_1039586188488119,Gen,0,24ebbe1f699c041ed3fbbdbbe04fbde1,"EMA(60,'oi004_3_10_1')",0.005846,0.005846,0,0,0,2026-04-23 03:32:57.532034
18175,ultron_1092357116687115,Gen,0,d5f01d5c50c76d0f972e04bf8a7db16c,"SQRT(MAPOSITIVE(30,'dv002_1_3_1'))",0.005412,0.005412,0,0,0,2026-04-23 08:23:54.554723
18176,ultron_1095600188763035,Reproduction,1,a54c3316b4f83eb28293810370047d08,"WMA(5,WMA(90,WMA(5,SIGLOG10ABS('oi004_2_5_1'))))",0.004094,0.004094,0,0,0,2026-04-23 05:04:24.004232
18178,ultron_1021533000875589,Gen,0,ba5dc4d61457643bf2324f6e27c6d436,"EMA(60,'oi022_5_15_0')",0.001085,0.001085,0,0,0,2026-04-23 06:29:53.183472
18179,ultron_1064408898673766,Gen,0,ec63743d7de579fb20a8d8068b162d8c,"MADecay(240,'oi004_1_3_1')",0.001074,0.001074,0,0,0,2026-04-23 08:29:34.052977

In [10]:
new_program

,name,method,gen,features,formual,final_fitness,raw_fitness,max_corr,penalty,alpha,update_time
0,ultron_1086340087875575,Gen,0,5bcf5da3c8961ef229414697d94243a6,"EMA(10,'tc008_5_15_0')",0.060898,0.060898,0,0,0,2026-05-05 06:42:31.442847
1,ultron_1009329337460366,Gen,0,2cebadf7c111bbc523ecdbeacc0ec837,"EMA(10,'cr042_1_3_1')",0.059792,0.059792,0,0,0,2026-05-06 17:32:49.504687
2,ultron_1007676351748701,Gen,0,da4f3fd65d83f73516bab8bfdeb95ec6,"EMA(5,MDIFF(10,'tv004_5_15_0'))",0.057222,0.057222,0,0,0,2026-05-03 18:57:12.711224
3,ultron_1064609757261927,Gen,0,2f94caf677335e1a736c799abeb02d0c,"EMA(5,'tc004_1_2_5_0')",0.057031,0.057031,0,0,0,2026-05-06 22:19:23.726364
4,ultron_1084360519926669,Hoist Mutation,1,302604235d9a5a2b1244e70fe9c6bf00,"SUBBED('tc009_1_2_5_5_1',MAPOSITIVE(240,'cr011...",0.056712,0.056712,0,0,0,2026-05-05 06:20:43.049190
...,...,...,...,...,...,...,...,...,...,...,...
18175,ultron_1092357116687115,Gen,0,d5f01d5c50c76d0f972e04bf8a7db16c,"SQRT(MAPOSITIVE(30,'dv002_1_3_1'))",0.005412,0.005412,0,0,0,2026-04-23 08:23:54.554723
18176,ultron_1095600188763035,Reproduction,1,a54c3316b4f83eb28293810370047d08,"WMA(5,WMA(90,WMA(5,SIGLOG10ABS('oi004_2_5_1'))))",0.004094,0.004094,0,0,0,2026-04-23 05:04:24.004232
18177,ultron_1030255680065207,Gen,0,39d622ad432d2eeeb9d2622b10f1f1bc,"MVHF(240,'tv014_3_10_1')",0.003042,0.003042,0,0,0,2026-04-23 06:33:01.718730
18178,ultron_1021533000875589,Gen,0,ba5dc4d61457643bf2324f6e27c6d436,"EMA(60,'oi022_5_15_0')",0.001085,0.001085,0,0,0,2026-04-23 06:29:53.183472
18179,ultron_1064408898673766,Gen,0,ec63743d7de579fb20a8d8068b162d8c,"MADecay(240,'oi004_1_3_1')",0.001074,0.001074,0,0,0,2026-04-23 08:29:34.052977

In [11]:
# 18180 / 5

In [12]:
# import os, math

# base_postion = 500
# count = math.ceil(new_program.shape[0] / base_postion)

# for i in range(0, count):
#     t1 = new_program.loc[i * base_postion: (i+1) * base_postion]
#     t2 = t1.reset_index(drop=True)
#     t2.to_feather(os.path.join("temp","all_bak", "{}.feather".format(i)))

In [13]:
import os, math,random
import pandas as pd

In [14]:
start_date_str = '2026-01-06'
end_date_str = '2026-06-01'

In [15]:
base_postion = 1000
count = math.ceil(new_program.shape[0] / base_postion)

In [16]:
current_date = pd.to_datetime(start_date_str)
end_date = pd.to_datetime(end_date_str)

In [17]:
filenames = []

for _ in range(count):
    filenames.append(current_date.strftime('%Y%m%d'))
    step = random.randint(1, 3) 
    current_date += pd.Timedelta(days=step)
    if current_date > end_date:
        print(f"[警告] 生成的文件名日期已超过设定的 {end_date_str}！")

In [18]:
os.makedirs(os.path.join("temp", "all_bak"), exist_ok=True)

In [19]:
for i in range(0, count):
    # 使用 iloc 避免边界数据重复
    t1 = new_program.iloc[i * base_postion : (i+1) * base_postion]
    t2 = t1.reset_index(drop=True)
    
    # 取出刚刚生成的日期字符串作为文件名
    current_filename = filenames[i]
    save_path = os.path.join("temp", "all_bak", f"{current_filename}.feather")
    
    t2.to_feather(save_path)