In [1]:
import pandas as pd
import numpy as np

In [2]:
# 加载行情数据
price_data = pd.read_parquet('/home/dev1/future_min1/20200102_20250313_bar.parquet')[['twap']].reset_index()
print("行情数据形状:", price_data.shape)
print("日期范围:", price_data['date'].min(), "-", price_data['date'].max())

行情数据形状: (1057822, 4)
日期范围: 20200102 - 20250313

In [3]:
price_data

             date minTime    Code         twap
0        20200102  093100  IC2001  5305.680000
1        20200102  093200  IC2001  5301.530000
2        20200102  093300  IC2001  5299.838333
3        20200102  093400  IC2001  5297.598333
4        20200102  093500  IC2001  5289.985000
...           ...     ...     ...          ...
1057817  20250313  145600  IM2503  6429.525000
1057818  20250313  145700  IM2503  6429.686667
1057819  20250313  145800  IM2503  6430.576667
1057820  20250313  145900  IM2503  6426.653333
1057821  20250313  150000  IM2503  6427.053333

[1057822 rows x 4 columns]

In [4]:
im_data = price_data[price_data['Code'].str.startswith('IM')].copy()
print("\nIM 合约数据形状:", im_data.shape)
print("IM 合约日期范围:", im_data['date'].min(), "-", im_data['date'].max())
print("IM 合约数量:", im_data['Code'].nunique())

IM 合约数据形状: (153358, 4)
IM 合约日期范围: 20220722 - 20250313
IM 合约数量: 32

In [5]:
def select_main_contract(df):
    """筛选每日主力合约（Code 最大值）"""
    return df.groupby('date', group_keys=False).apply(
        lambda x: x[x['Code'] == x['Code'].max()]
    ).reset_index(drop=True)
    
main_contract_data = select_main_contract(im_data)
print("\n主力合约数据形状:", main_contract_data.shape)
print("交易日数量:", main_contract_data['date'].nunique())
print("\n主力合约示例:")
main_contract_data.head(10)

主力合约数据形状: (153358, 4)
交易日数量: 639

主力合约示例:

       date minTime    Code         twap
0  20220722  093100  IM2208  7052.306087
1  20220722  093200  IM2208  7066.660000
2  20220722  093300  IM2208  7080.682759
3  20220722  093400  IM2208  7074.083810
4  20220722  093500  IM2208  7072.356250
5  20220722  093600  IM2208  7076.723478
6  20220722  093700  IM2208  7073.693182
7  20220722  093800  IM2208  7068.310870
8  20220722  093900  IM2208  7071.979775
9  20220722  094000  IM2208  7076.816667

In [6]:
# 查看主力合约换月情况
main_contracts_by_date = main_contract_data.groupby('date')['Code'].first()
print("\n主力合约换月情况:")
print(main_contracts_by_date.head(30))

主力合约换月情况:
date
20220722    IM2208
20220725    IM2208
20220726    IM2208
20220727    IM2208
20220728    IM2208
20220729    IM2208
20220801    IM2208
20220802    IM2208
20220803    IM2208
20220804    IM2208
20220805    IM2208
20220808    IM2208
20220809    IM2208
20220810    IM2208
20220811    IM2208
20220812    IM2208
20220815    IM2208
20220816    IM2208
20220817    IM2208
20220818    IM2208
20220819    IM2208
20220822    IM2209
20220823    IM2209
20220824    IM2209
20220825    IM2209
20220826    IM2209
20220829    IM2209
20220830    IM2209
20220831    IM2209
20220901    IM2209
Name: Code, dtype: object

In [8]:
# 统计每个主力合约的交易日数
contract_counts = main_contracts_by_date.value_counts()
print("\n主力合约交易日统计:")
print(contract_counts.head())

主力合约交易日统计:
IM2412    25
IM2301    24
IM2304    24
IM2406    24
IM2401    24
Name: Code, dtype: int64

In [ ]:
def generate_position_signals(price_data: pd.DataFrame, interval: int = 15) -> pd.DataFrame:
    time_index = {}
    for (date, code), group in price_data.groupby(['date', 'Code']):
        times = sorted(group['minTime'].unique())
        time_index[(date, code)] = times
        
    all_signals = []
    
    for (date, code), times in time_index.items():
        signals = []