In [1]:
import pandas  as pd
import numpy as np
import pdb, os, datetime, itertools, time, hashlib
from dotenv import load_dotenv

load_dotenv()
from lib.flp001 import *

In [2]:
method = 'bicso3'
task_id = '122001'
session = '20260619'
instruments = 'mab'
period = 15

In [3]:
results = load_data(method=method, task_id=task_id, instruments=instruments, 
          period=period, session=session, category=2)
results['name'] = results['name'].astype(int).astype(int)
results['abs_ic'] = np.abs(results['ic_mean'])
results['abs_icir'] = np.abs(results['icir'])
results1 = results
results1.tail()

./records/bicso3/mab/rulex/122001/nxt1_ret_15h/d20260619

,name,expression,avg_ret,total_ret,sharpe,ann_sharpe,max_dd,calmar,win_rate,pl_ratio,...,icir,turnover,factor_ac,ret_ac,roll_win,resampling_win,holding_profit,category,abs_ic,abs_icir
37,10718391,"MPERCENT(90,'tv017_2_5_1')",0.36,502.87,0.02,1.53,-12.81,1.63,52.09,1.10,...,-0.1787,0.4642,-0.0100,-0.0925,None,None,None,d,0.0484,0.1787
38,10308180,"MMaxDiff(240,MPERCENT(30,'tc014_1_2_5_1'))",0.35,441.84,0.02,1.53,-13.49,1.45,51.79,1.10,...,-0.1698,0.4579,-0.0574,-0.0924,None,None,None,d,0.0457,0.1698
39,10689486,"MQUANTILE(90,'tc012_1_2_5_1')",0.35,497.63,0.02,1.53,-12.81,1.62,52.10,1.10,...,-0.1783,0.4642,-0.0103,-0.0925,None,None,None,d,0.0483,0.1783
40,10216933,"MPERCENT(120,MMaxDiff(240,MCPS(90,'cr042_2_5_1...",0.33,445.63,0.02,1.58,-12.25,1.60,51.89,1.09,...,0.1706,0.4458,-0.0067,-0.0881,None,None,None,d,0.0455,0.1706
41,10587202,"MMinDiff(60,MPERCENT(90,'oi037_2_5_1'))",0.26,264.23,0.02,1.21,-11.99,1.22,51.64,1.08,...,-0.1538,0.4347,-0.0108,-0.0897,None,None,None,d,0.0413,0.1538

In [4]:
# results[results.expression.isin(drafit_data.formula.tolist())].to_csv("rbb_drafit.csv")
results['abs_ic'].median()

0.041999999999999996

In [5]:
### IC大于0.03  ## 夏普大于2.2  # 卡玛大于2.5
results = results[(results['abs_ic']>0.04) & (results['ann_sharpe']>1.2) & (
    results['calmar']>1.2)].reset_index(drop=True)

In [6]:
results

,name,expression,avg_ret,total_ret,sharpe,ann_sharpe,max_dd,calmar,win_rate,pl_ratio,...,icir,turnover,factor_ac,ret_ac,roll_win,resampling_win,holding_profit,category,abs_ic,abs_icir
0,10391701,"MDIFF(120,SIGLOG10ABS(MRANK(90,'tc006_3_10_1')))",0.39,610.01,0.02,1.61,-18.35,1.25,51.76,1.10,...,-0.1599,0.5164,0.0112,-0.0911,None,None,None,d,0.0426,0.1599
1,10804682,"MQUANTILE(90,SIGLOG2ABS('tc014_2_3_5_1'))",0.34,455.98,0.02,1.43,-14.52,1.37,51.83,1.09,...,-0.1691,0.5008,-0.0228,-0.0916,None,None,None,d,0.0452,0.1691
2,10618056,"MPERCENT(120,MPERCENT(120,MPERCENT(120,'cr042_...",0.32,393.68,0.02,1.51,-12.23,1.50,51.76,1.09,...,-0.1501,0.4450,0.0119,-0.0899,None,None,None,d,0.0404,0.1501
3,10742646,"MQUANTILE(240,MQUANTILE(240,'oi039_2_5_1'))",0.33,445.01,0.02,1.42,-14.92,1.31,52.03,1.09,...,0.1658,0.4659,0.0087,-0.0847,None,None,None,d,0.0450,0.1658
4,10405251,"WMA(30,'dv002_1_3_1')",0.39,623.75,0.02,1.30,-16.43,1.41,51.98,1.09,...,-0.3821,0.5615,0.3354,-0.0876,None,None,None,d,0.0950,0.3821
5,10512288,"MCPS(240,MADiff(60,'ixy014_2_5_1'))",0.32,410.12,0.02,1.52,-13.11,1.43,52.23,1.09,...,0.1950,0.4247,-0.0107,-0.0876,None,None,None,d,0.0513,0.1950
6,10630659,"MCPS(60,SIGLOG2ABS('oi037_3_10_1'))",0.28,313.76,0.02,1.26,-12.82,1.26,52.09,1.08,...,0.2275,0.4754,0.0160,-0.0861,None,None,None,d,0.0588,0.2275
7,10967569,"MPERCENT(30,'oi034_2_5_1')",0.35,442.10,0.02,1.56,-10.48,1.86,51.76,1.10,...,-0.1681,0.4613,-0.0637,-0.0918,None,None,None,d,0.0453,0.1681
8,10161068,"MQUANTILE(240,'iv012_2_5_1')",0.33,434.41,0.02,1.32,-15.85,1.22,51.79,1.08,...,0.1848,0.5238,0.0153,-0.0863,None,None,None,d,0.0494,0.1848
9,10987270,"MPERCENT(120,ACOS(MPERCENT(120,MCPS(90,'cr042_...",0.33,447.24,0.02,1.59,-12.11,1.62,51.92,1.09,...,-0.1549,0.4462,-0.0035,-0.0873,None,None,None,d,0.0416,0.1549
10,10383132,"MADiff(240,MQUANTILE(15,MADiff(240,'tn003_1_2_...",0.31,406.73,0.02,1.36,-11.77,1.59,51.49,1.09,...,-0.1587,0.4638,-0.1029,-0.0876,None,None,None,d,0.0428,0.1587
11,10094905,"FRAC(MPERCENT(30,'oi034_2_5_1'))",0.35,442.10,0.02,1.56,-10.48,1.86,51.76,1.10,...,-0.1681,0.4613,-0.0637,-0.0918,None,None,None,d,0.0453,0.1681
12,10122058,"MPERCENT(120,ACOS(MPERCENT(120,MMaxDiff(240,'c...",0.32,411.95,0.02,1.52,-13.88,1.35,51.86,1.09,...,0.1507,0.4459,-0.0034,-0.0899,None,None,None,d,0.0404,0.1507
13,10092195,"MPERCENT(90,MCPS(240,'ixy014_2_5_1'))",0.31,357.10,0.02,1.45,-14.03,1.24,51.64,1.09,...,0.1596,0.4423,-0.0140,-0.0937,None,None,None,d,0.0424,0.1596
14,10884841,"MPERCENT(120,MCPS(90,'cr042_2_5_1'))",0.33,443.05,0.02,1.55,-12.36,1.58,51.84,1.09,...,0.1706,0.4459,-0.0077,-0.0884,None,None,None,d,0.0456,0.1706
15,10174774,"MCPS(240,MDIFF(30,MDIFF(30,'ixy014_2_5_1')))",0.31,398.77,0.02,1.51,-13.25,1.39,52.30,1.09,...,0.2542,0.4183,0.0116,-0.0876,None,None,None,d,0.0667,0.2542
16,10233714,"MRes(60,'rv001_3_10_1_2','ixy014_2_5_1')",0.30,378.51,0.02,1.44,-14.22,1.26,51.91,1.09,...,-0.2416,0.4188,0.0166,-0.0876,None,None,None,d,0.0638,0.2416
17,10740829,"MQUANTILE(240,'oi039_2_5_1')",0.34,460.17,0.02,1.43,-14.44,1.38,52.10,1.09,...,0.2056,0.4663,0.0083,-0.0859,None,None,None,d,0.0553,0.2056
18,10415811,"MQUANTILE(15,'tv017_2_5_1')",0.30,300.93,0.02,1.31,-10.34,1.52,51.60,1.09,...,-0.1534,0.4431,-0.0599,-0.0992,None,None,None,d,0.0413,0.1534
19,10302174,"MPERCENT(120,SUBBED('cr003_1_3_1','oi037_3_10_...",0.29,333.38,0.02,1.23,-13.16,1.27,51.73,1.08,...,0.1543,0.5048,0.0114,-0.0878,None,None,None,d,0.0404,0.1543
20,10443078,"EMA(60,'dv002_1_3_1')",0.40,640.53,0.02,1.30,-12.49,1.88,52.30,1.09,...,-0.5934,0.5412,0.6253,-0.0685,None,None,None,d,0.1426,0.5934
21,10976528,"MCPS(240,MDIFF(30,'ixy014_2_5_1'))",0.31,398.77,0.02,1.51,-13.25,1.39,52.30,1.09,...,0.2542,0.4183,0.0116,-0.0876,None,None,None,d,0.0667,0.2542
22,10718391,"MPERCENT(90,'tv017_2_5_1')",0.36,502.87,0.02,1.53,-12.81,1.63,52.09,1.10,...,-0.1787,0.4642,-0.0100,-0.0925,None,None,None,d,0.0484,0.1787
23,10308180,"MMaxDiff(240,MPERCENT(30,'tc014_1_2_5_1'))",0.35,441.84,0.02,1.53,-13.49,1.45,51.79,1.10,...,-0.1698,0.4579,-0.0574,-0.0924,None,None,None,d,0.0457,0.1698
24,10689486,"MQUANTILE(90,'tc012_1_2_5_1')",0.35,497.63,0.02,1.53,-12.81,1.62,52.10,1.10,...,-0.1783,0.4642,-0.0103,-0.0925,None,None,None,d,0.0483,0.1783
25,10216933,"MPERCENT(120,MMaxDiff(240,MCPS(90,'cr042_2_5_1...",0.33,445.63,0.02,1.58,-12.25,1.60,51.89,1.09,...,0.1706,0.4458,-0.0067,-0.0881,None,None,None,d,0.0455,0.1706
26,10587202,"MMinDiff(60,MPERCENT(90,'oi037_2_5_1'))",0.26,264.23,0.02,1.21,-11.99,1.22,51.64,1.08,...,-0.1538,0.4347,-0.0108,-0.0897,None,None,None,d,0.0413,0.1538

In [7]:
results = results[['expression','name']]
results['path'] = (base_path + '/' + str(method) + '/' + instruments + '/rulex' + '/' + str(task_id) + "/nxt1_ret_{0}h".format(period) \
    + "/d{0}".format(session) + '/plot/' + + results['name'].astype(str) + '.png')
                   
results['path'] = results['path'].apply(make_clickable)

In [9]:
### IC大于 total ic 0.017
to_html(results)

In [9]:
results1.sort_values(by=['icir'],ascending=False).max()

name                                    10989681
expression        WMA(5,MDIFF(15,'tv007_1_2_1'))
avg_ret                                     0.25
total_ret                               11492.64
sharpe                                      0.03
ann_sharpe                                  3.11
max_dd                                     -8.86
calmar                                      2.87
win_rate                                   52.32
pl_ratio                                    1.12
ic_mean                                   0.0607
icir                                      0.2293
turnover                                  0.4569
factor_ac                                 0.9687
ret_ac                                   -0.0686
roll_win                                    None
resampling_win                              None
holding_profit                              None
category                                       d
abs_ic                                    0.0848
abs_icir                                  0.3218
dtype: object