#### 投研环境中， 自行合成数据和通联数据对比

In [1]:
import os
from dotenv import load_dotenv

load_dotenv()
import pandas as pd

In [2]:
from config.contract import TRADING_TIME_MAPPING
from kdutils.data import fetch_main_market,  fetch_local_market1
from lib.attr001.ftd001 import filter_trading_time
from lib.ret001 import create_chg, create_yields

/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:11: UserWarning: if use distributed calculating, please configure MQ_URL
  warnings.warn('if use distributed calculating, please configure MQ_URL')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:15: UserWarning: if use distributed calculating, please configure NTN_URL
  warnings.warn('if use distributed calculating, please configure NTN_URL')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:19: UserWarning: if use memory database, please configure KN_MG
  warnings.warn('if use memory database, please configure KN_MG')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:27: UserWarning: if use trader, please configure ATL_URL
  warnings.warn('if use trader, please configure ATL_URL')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:31: UserWarning: if use trader, please configure IREY_URL
  warnings.warn('if use trader, please configure IREY_URL')

In [3]:
code = 'MA'
trading_sessions = TRADING_TIME_MAPPING[code]
begin_date = '2025-01-01' #'2025-01-01'
end_data = '2026-06-30'#'2026-01-01'

In [4]:
keep_columns = ['trade_time','code','symbol', 'open','high','low','close','vwap','openint','volume','value']

In [5]:
research_data = fetch_local_market1(base_path=os.environ['BAR_FUT_DIRS'],
                                       begin_date=begin_date,
                                       end_date=end_data,
                                       keep_symbol=True,
                                       method=None,
                                       codes=[code])
research_data = research_data[keep_columns]
research_data['trade_time'] = pd.to_datetime(research_data['trade_time'])
research_data = research_data.set_index(['trade_time','code'])
research_data = filter_trading_time(data=research_data, trading_sessions=trading_sessions).sort_values(by=['trade_time','code'])
research_data.head()

/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250102/MA505_20250102.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250103/MA505_20250103.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250106/MA505_20250106.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250107/MA505_20250107.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250108/MA505_20250108.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250109/MA505_20250109.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250110/MA505_20250110.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250113/MA505_20250113.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250114/MA505_20250114.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250115/MA505_20250115.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250116/MA505_20250116.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250117/MA505_20250117.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250120/MA505_20250120.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250121/MA505_20250121.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250122/MA505_20250122.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250123/MA505_20250123.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250124/MA505_20250124.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250127/MA505_20250127.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250205/MA505_20250205.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250206/MA505_20250206.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250207/MA505_20250207.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250210/MA505_20250210.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250211/MA505_20250211.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250212/MA505_20250212.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250213/MA505_20250213.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250214/MA505_20250214.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250217/MA505_20250217.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250218/MA505_20250218.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250219/MA505_20250219.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250220/MA505_20250220.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250221/MA505_20250221.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250224/MA505_20250224.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250225/MA505_20250225.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250226/MA505_20250226.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250227/MA505_20250227.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250228/MA505_20250228.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250303/MA505_20250303.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250304/MA505_20250304.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250305/MA505_20250305.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250306/MA505_20250306.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250307/MA505_20250307.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250310/MA505_20250310.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250311/MA505_20250311.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250312/MA505_20250312.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250313/MA505_20250313.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250314/MA505_20250314.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250317/MA505_20250317.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250318/MA505_20250318.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250319/MA505_20250319.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250320/MA505_20250320.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250321/MA505_20250321.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250324/MA505_20250324.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250325/MA505_20250325.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250326/MA505_20250326.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250327/MA505_20250327.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250328/MA505_20250328.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250331/MA505_20250331.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250401/MA505_20250401.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250402/MA505_20250402.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250403/MA505_20250403.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250407/MA505_20250407.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250408/MA505_20250408.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250409/MA505_20250409.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250410/MA505_20250410.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250411/MA505_20250411.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250414/MA509_20250414.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250415/MA509_20250415.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250416/MA509_20250416.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250417/MA509_20250417.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250418/MA509_20250418.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250421/MA509_20250421.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250422/MA509_20250422.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250423/MA509_20250423.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250424/MA509_20250424.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250425/MA509_20250425.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250428/MA509_20250428.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250429/MA509_20250429.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250430/MA509_20250430.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250506/MA509_20250506.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250507/MA509_20250507.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250508/MA509_20250508.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250509/MA509_20250509.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250512/MA509_20250512.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250513/MA509_20250513.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250514/MA509_20250514.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250515/MA509_20250515.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250516/MA509_20250516.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250519/MA509_20250519.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250520/MA509_20250520.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250521/MA509_20250521.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250523/MA509_20250523.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250526/MA509_20250526.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250528/MA509_20250528.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250529/MA509_20250529.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250530/MA509_20250530.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250603/MA509_20250603.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250604/MA509_20250604.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250605/MA509_20250605.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250606/MA509_20250606.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250609/MA509_20250609.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250610/MA509_20250610.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250611/MA509_20250611.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250612/MA509_20250612.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250613/MA509_20250613.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250616/MA509_20250616.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250617/MA509_20250617.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250618/MA509_20250618.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250619/MA509_20250619.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250620/MA509_20250620.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250623/MA509_20250623.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250624/MA509_20250624.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250625/MA509_20250625.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250626/MA509_20250626.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250627/MA509_20250627.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250630/MA509_20250630.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250701/MA509_20250701.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250702/MA509_20250702.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250703/MA509_20250703.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250704/MA509_20250704.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250707/MA509_20250707.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250708/MA509_20250708.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250709/MA509_20250709.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250710/MA509_20250710.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250711/MA509_20250711.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250714/MA509_20250714.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250715/MA509_20250715.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250716/MA509_20250716.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250717/MA509_20250717.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250718/MA509_20250718.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250721/MA509_20250721.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250722/MA509_20250722.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250723/MA509_20250723.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250724/MA509_20250724.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250725/MA509_20250725.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250728/MA509_20250728.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250729/MA509_20250729.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250730/MA509_20250730.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250731/MA509_20250731.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250801/MA509_20250801.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250804/MA509_20250804.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250805/MA509_20250805.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250806/MA509_20250806.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250807/MA509_20250807.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250808/MA509_20250808.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250811/MA509_20250811.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250812/MA601_20250812.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250813/MA601_20250813.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250814/MA601_20250814.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250815/MA601_20250815.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250818/MA601_20250818.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250819/MA601_20250819.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250820/MA601_20250820.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250821/MA601_20250821.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250822/MA601_20250822.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250825/MA601_20250825.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250826/MA601_20250826.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250827/MA601_20250827.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250828/MA601_20250828.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250829/MA601_20250829.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250901/MA601_20250901.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250902/MA601_20250902.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250903/MA601_20250903.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250904/MA601_20250904.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250905/MA601_20250905.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250908/MA601_20250908.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250909/MA601_20250909.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250910/MA601_20250910.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250911/MA601_20250911.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250912/MA601_20250912.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250915/MA601_20250915.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250916/MA601_20250916.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250917/MA601_20250917.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250918/MA601_20250918.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250919/MA601_20250919.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250922/MA601_20250922.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250923/MA601_20250923.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250924/MA601_20250924.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250925/MA601_20250925.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250926/MA601_20250926.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250929/MA601_20250929.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250930/MA601_20250930.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251009/MA601_20251009.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251010/MA601_20251010.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251013/MA601_20251013.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251014/MA601_20251014.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251015/MA601_20251015.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251016/MA601_20251016.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251017/MA601_20251017.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251020/MA601_20251020.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251021/MA601_20251021.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251022/MA601_20251022.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251023/MA601_20251023.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251024/MA601_20251024.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251027/MA601_20251027.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251028/MA601_20251028.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251029/MA601_20251029.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251030/MA601_20251030.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251031/MA601_20251031.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251103/MA601_20251103.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251104/MA601_20251104.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251105/MA601_20251105.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251106/MA601_20251106.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251107/MA601_20251107.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251110/MA601_20251110.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251111/MA601_20251111.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251112/MA601_20251112.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251113/MA601_20251113.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251114/MA601_20251114.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251117/MA601_20251117.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251118/MA601_20251118.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251119/MA601_20251119.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251120/MA601_20251120.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251121/MA601_20251121.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251124/MA601_20251124.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251125/MA601_20251125.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251126/MA601_20251126.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251127/MA601_20251127.feather

,trade_time,code,symbol,open,high,low,close,vwap,openint,volume,value
0,2025-01-02 09:00:00,MA,MA505,2710.0,2724.0,2710.0,2721.0,2718.719204,928459.0,27041.0,73516886.0
1,2025-01-02 09:01:00,MA,MA505,2722.0,2724.0,2715.0,2716.0,2718.000000,931230.0,14175.0,38527650.0
2,2025-01-02 09:02:00,MA,MA505,2717.0,2722.0,2714.0,2721.0,2718.000000,933435.0,9813.0,26671734.0
3,2025-01-02 09:03:00,MA,MA505,2720.0,2720.0,2715.0,2716.0,2718.000000,934454.0,6654.0,18085572.0
4,2025-01-02 09:04:00,MA,MA505,2716.0,2716.0,2711.0,2712.0,2718.000000,935887.0,6676.0,18145368.0

In [6]:
research_data = fetch_local_market1(base_path=os.environ['BAR_FUT_DIRS'],
                                       begin_date=begin_date,
                                       end_date=end_data,
                                       keep_symbol=True,
                                       codes=[code])
research_data = research_data[keep_columns]
research_data['trade_time'] = pd.to_datetime(research_data['trade_time'])
research_data = research_data.set_index(['trade_time','code'])
research_data = filter_trading_time(data=research_data, trading_sessions=trading_sessions).sort_values(by=['trade_time','code'])
research_data.head()

/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250102/MA505_20250102.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250103/MA505_20250103.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250106/MA505_20250106.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250107/MA505_20250107.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250108/MA505_20250108.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250109/MA505_20250109.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250110/MA505_20250110.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250113/MA505_20250113.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250114/MA505_20250114.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250115/MA505_20250115.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250116/MA505_20250116.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250117/MA505_20250117.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250120/MA505_20250120.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250121/MA505_20250121.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250122/MA505_20250122.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250123/MA505_20250123.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250124/MA505_20250124.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250127/MA505_20250127.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250205/MA505_20250205.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250206/MA505_20250206.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250207/MA505_20250207.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250210/MA505_20250210.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250211/MA505_20250211.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250212/MA505_20250212.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250213/MA505_20250213.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250214/MA505_20250214.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250217/MA505_20250217.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250218/MA505_20250218.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250219/MA505_20250219.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250220/MA505_20250220.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250221/MA505_20250221.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250224/MA505_20250224.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250225/MA505_20250225.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250226/MA505_20250226.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250227/MA505_20250227.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250228/MA505_20250228.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250303/MA505_20250303.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250304/MA505_20250304.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250305/MA505_20250305.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250306/MA505_20250306.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250307/MA505_20250307.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250310/MA505_20250310.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250311/MA505_20250311.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250312/MA505_20250312.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250313/MA505_20250313.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250314/MA505_20250314.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250317/MA505_20250317.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250318/MA505_20250318.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250319/MA505_20250319.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250320/MA505_20250320.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250321/MA505_20250321.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250324/MA505_20250324.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250325/MA505_20250325.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250326/MA505_20250326.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250327/MA505_20250327.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250328/MA505_20250328.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250331/MA505_20250331.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250401/MA505_20250401.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250402/MA505_20250402.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250403/MA505_20250403.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250407/MA505_20250407.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250408/MA505_20250408.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250409/MA505_20250409.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250410/MA505_20250410.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250411/MA505_20250411.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250414/MA509_20250414.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250415/MA509_20250415.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250416/MA509_20250416.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250417/MA509_20250417.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250418/MA509_20250418.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250421/MA509_20250421.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250422/MA509_20250422.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250423/MA509_20250423.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250424/MA509_20250424.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250425/MA509_20250425.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250428/MA509_20250428.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250429/MA509_20250429.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250430/MA509_20250430.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250506/MA509_20250506.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250507/MA509_20250507.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250508/MA509_20250508.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250509/MA509_20250509.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250512/MA509_20250512.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250513/MA509_20250513.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250514/MA509_20250514.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250515/MA509_20250515.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250516/MA509_20250516.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250519/MA509_20250519.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250520/MA509_20250520.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250521/MA509_20250521.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250523/MA509_20250523.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250526/MA509_20250526.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250528/MA509_20250528.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250529/MA509_20250529.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250530/MA509_20250530.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250603/MA509_20250603.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250604/MA509_20250604.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250605/MA509_20250605.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250606/MA509_20250606.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250609/MA509_20250609.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250610/MA509_20250610.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250611/MA509_20250611.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250612/MA509_20250612.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250613/MA509_20250613.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250616/MA509_20250616.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250617/MA509_20250617.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250618/MA509_20250618.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250619/MA509_20250619.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250620/MA509_20250620.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250623/MA509_20250623.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250624/MA509_20250624.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250625/MA509_20250625.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250626/MA509_20250626.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250627/MA509_20250627.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250630/MA509_20250630.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250701/MA509_20250701.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250702/MA509_20250702.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250703/MA509_20250703.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250704/MA509_20250704.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250707/MA509_20250707.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250708/MA509_20250708.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250709/MA509_20250709.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250710/MA509_20250710.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250711/MA509_20250711.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250714/MA509_20250714.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250715/MA509_20250715.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250716/MA509_20250716.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250717/MA509_20250717.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250718/MA509_20250718.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250721/MA509_20250721.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250722/MA509_20250722.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250723/MA509_20250723.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250724/MA509_20250724.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250725/MA509_20250725.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250728/MA509_20250728.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250729/MA509_20250729.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250730/MA509_20250730.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250731/MA509_20250731.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250801/MA509_20250801.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250804/MA509_20250804.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250805/MA509_20250805.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250806/MA509_20250806.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250807/MA509_20250807.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250808/MA509_20250808.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250811/MA509_20250811.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250812/MA601_20250812.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250813/MA601_20250813.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250814/MA601_20250814.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250815/MA601_20250815.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250818/MA601_20250818.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250819/MA601_20250819.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250820/MA601_20250820.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250821/MA601_20250821.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250822/MA601_20250822.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250825/MA601_20250825.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250826/MA601_20250826.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250827/MA601_20250827.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250828/MA601_20250828.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250829/MA601_20250829.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250901/MA601_20250901.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250902/MA601_20250902.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250903/MA601_20250903.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250904/MA601_20250904.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250905/MA601_20250905.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250908/MA601_20250908.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250909/MA601_20250909.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250910/MA601_20250910.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250911/MA601_20250911.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250912/MA601_20250912.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250915/MA601_20250915.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250916/MA601_20250916.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250917/MA601_20250917.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250918/MA601_20250918.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250919/MA601_20250919.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250922/MA601_20250922.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250923/MA601_20250923.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250924/MA601_20250924.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250925/MA601_20250925.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250926/MA601_20250926.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250929/MA601_20250929.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20250930/MA601_20250930.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251009/MA601_20251009.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251010/MA601_20251010.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251013/MA601_20251013.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251014/MA601_20251014.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251015/MA601_20251015.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251016/MA601_20251016.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251017/MA601_20251017.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251020/MA601_20251020.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251021/MA601_20251021.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251022/MA601_20251022.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251023/MA601_20251023.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251024/MA601_20251024.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251027/MA601_20251027.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251028/MA601_20251028.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251029/MA601_20251029.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251030/MA601_20251030.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251031/MA601_20251031.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251103/MA601_20251103.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251104/MA601_20251104.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251105/MA601_20251105.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251106/MA601_20251106.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251107/MA601_20251107.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251110/MA601_20251110.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251111/MA601_20251111.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251112/MA601_20251112.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251113/MA601_20251113.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251114/MA601_20251114.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251117/MA601_20251117.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251118/MA601_20251118.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251119/MA601_20251119.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251120/MA601_20251120.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251121/MA601_20251121.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251124/MA601_20251124.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251125/MA601_20251125.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251126/MA601_20251126.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20251127/MA601_20251127.feather

,trade_time,code,symbol,open,high,low,close,vwap,openint,volume,value
0,2025-01-02 09:00:00,MA,MA505,2143.385070,2154.457908,2143.385070,2152.085157,2150.281237,928459.0,27041.0,73516886.0
1,2025-01-02 09:01:00,MA,MA505,2152.876074,2154.457908,2147.339655,2148.130572,2149.712406,931230.0,14175.0,38527650.0
2,2025-01-02 09:02:00,MA,MA505,2148.921489,2152.876074,2146.548738,2152.085157,2149.712406,933435.0,9813.0,26671734.0
3,2025-01-02 09:03:00,MA,MA505,2151.294240,2151.294240,2147.339655,2148.130572,2149.712406,934454.0,6654.0,18085572.0
4,2025-01-02 09:04:00,MA,MA505,2148.130572,2148.130572,2144.175987,2144.966904,2149.712406,935887.0,6676.0,18145368.0

In [7]:
research_data

,trade_time,code,symbol,open,high,low,close,vwap,openint,volume,value
0,2025-01-02 09:00:00,MA,MA505,2143.385070,2154.457908,2143.385070,2152.085157,2150.281237,928459.0,27041.0,73516886.0
1,2025-01-02 09:01:00,MA,MA505,2152.876074,2154.457908,2147.339655,2148.130572,2149.712406,931230.0,14175.0,38527650.0
2,2025-01-02 09:02:00,MA,MA505,2148.921489,2152.876074,2146.548738,2152.085157,2149.712406,933435.0,9813.0,26671734.0
3,2025-01-02 09:03:00,MA,MA505,2151.294240,2151.294240,2147.339655,2148.130572,2149.712406,934454.0,6654.0,18085572.0
4,2025-01-02 09:04:00,MA,MA505,2148.130572,2148.130572,2144.175987,2144.966904,2149.712406,935887.0,6676.0,18145368.0
...,...,...,...,...,...,...,...,...,...,...,...
122837,2026-06-30 14:55:00,MA,MA609,2041.105525,2042.788911,2041.105525,2041.947218,2047.839069,704384.0,2690.0,6544770.0
122838,2026-06-30 14:56:00,MA,MA609,2041.947218,2042.788911,2041.105525,2041.947218,2047.839069,703974.0,2914.0,7089762.0
122839,2026-06-30 14:57:00,MA,MA609,2041.947218,2042.788911,2041.105525,2042.788911,2047.839069,703547.0,2046.0,4977918.0
122840,2026-06-30 14:58:00,MA,MA609,2041.947218,2043.630604,2041.105525,2042.788911,2047.839069,702203.0,4478.0,10894974.0
122841,2026-06-30 14:59:00,MA,MA609,2042.788911,2043.630604,2041.947218,2043.630604,2047.839069,700024.0,6224.0,15142992.0

In [8]:
bench_data = fetch_main_market(begin_date=begin_date,
                                     end_date=end_data,
                                     codes=[code],
                                     keep_symbol=True,
                                     forced_alignment=True)
bench_data['vwap'] = bench_data['vwap'] * bench_data['pcr_cumfactor']
bench_data = bench_data[keep_columns]
bench_data['trade_time'] = pd.to_datetime(bench_data['trade_time'])
bench_data = bench_data.set_index(['trade_time','code'])
bench_data = filter_trading_time(data=bench_data, trading_sessions=trading_sessions).sort_values(by=['trade_time','code'])

In [9]:
bench_data.tail()

,trade_time,code,symbol,open,high,low,close,vwap,openint,volume,value
113205,2026-06-30 22:55:00,MA,MA609,2032.688595,2033.530288,2031.846902,2032.688595,2032.346994,725062.0,2735.0,66039150.0
113206,2026-06-30 22:56:00,MA,MA609,2032.688595,2033.530288,2031.846902,2031.846902,2032.803767,724593.0,1257.0,30358270.0
113207,2026-06-30 22:57:00,MA,MA609,2031.846902,2032.688595,2031.846902,2031.846902,2032.263723,723723.0,1359.0,32812990.0
113208,2026-06-30 22:58:00,MA,MA609,2031.846902,2032.688595,2030.163516,2031.005209,2031.477770,722852.0,2832.0,68352060.0
113209,2026-06-30 22:59:00,MA,MA609,2030.163516,2031.846902,2028.480130,2029.321823,2030.407437,720897.0,5107.0,123195640.0

In [10]:
#research_data.set_index('trade_time').loc['2026-06-30 13:39']

In [11]:
bench_data.tail()

,trade_time,code,symbol,open,high,low,close,vwap,openint,volume,value
113205,2026-06-30 22:55:00,MA,MA609,2032.688595,2033.530288,2031.846902,2032.688595,2032.346994,725062.0,2735.0,66039150.0
113206,2026-06-30 22:56:00,MA,MA609,2032.688595,2033.530288,2031.846902,2031.846902,2032.803767,724593.0,1257.0,30358270.0
113207,2026-06-30 22:57:00,MA,MA609,2031.846902,2032.688595,2031.846902,2031.846902,2032.263723,723723.0,1359.0,32812990.0
113208,2026-06-30 22:58:00,MA,MA609,2031.846902,2032.688595,2030.163516,2031.005209,2031.477770,722852.0,2832.0,68352060.0
113209,2026-06-30 22:59:00,MA,MA609,2030.163516,2031.846902,2028.480130,2029.321823,2030.407437,720897.0,5107.0,123195640.0

In [12]:
research_data.set_index('trade_time').loc['2026-06-30'].tail(20)

,code,symbol,open,high,low,close,vwap,openint,volume,value
trade_time,,,,,,,,,,
2026-06-30 14:40:00,MA,MA609,2033.530288,2033.530288,2031.846902,2032.688595,2047.839069,716292.0,1118.0,2720094.0
2026-06-30 14:41:00,MA,MA609,2032.688595,2034.371981,2031.846902,2033.530288,2047.839069,716207.0,1545.0,3758985.0
2026-06-30 14:42:00,MA,MA609,2034.371981,2036.897060,2033.530288,2035.213674,2047.839069,714685.0,5692.0,13848636.0
2026-06-30 14:43:00,MA,MA609,2036.055367,2038.580446,2036.055367,2037.738753,2047.839069,713503.0,4036.0,9819588.0
2026-06-30 14:44:00,MA,MA609,2037.738753,2038.580446,2036.055367,2036.897060,2047.839069,713257.0,2662.0,6476646.0
2026-06-30 14:45:00,MA,MA609,2036.055367,2037.738753,2036.055367,2036.055367,2047.839069,713152.0,1486.0,3615438.0
2026-06-30 14:46:00,MA,MA609,2036.897060,2038.580446,2036.055367,2037.738753,2047.839069,712651.0,2263.0,5505879.0
2026-06-30 14:47:00,MA,MA609,2037.738753,2041.105525,2037.738753,2039.422139,2047.839069,711642.0,4545.0,11057985.0
2026-06-30 14:48:00,MA,MA609,2039.422139,2041.105525,2039.422139,2039.422139,2047.839069,711513.0,1702.0,4140966.0
2026-06-30 14:49:00,MA,MA609,2040.263832,2041.105525,2039.422139,2041.105525,2047.839069,710957.0,1567.0,3812511.0
2026-06-30 14:50:00,MA,MA609,2041.105525,2044.472297,2041.105525,2042.788911,2047.839069,708051.0,8229.0,20021157.0
2026-06-30 14:51:00,MA,MA609,2042.788911,2044.472297,2041.947218,2044.472297,2047.839069,708022.0,4242.0,10320786.0
2026-06-30 14:52:00,MA,MA609,2045.313990,2045.313990,2042.788911,2043.630604,2047.839069,706610.0,6760.0,16447080.0
2026-06-30 14:53:00,MA,MA609,2044.472297,2045.313990,2043.630604,2043.630604,2047.839069,705970.0,3877.0,9432741.0
2026-06-30 14:54:00,MA,MA609,2043.630604,2045.313990,2039.422139,2040.263832,2047.839069,705133.0,5540.0,13478820.0
2026-06-30 14:55:00,MA,MA609,2041.105525,2042.788911,2041.105525,2041.947218,2047.839069,704384.0,2690.0,6544770.0
2026-06-30 14:56:00,MA,MA609,2041.947218,2042.788911,2041.105525,2041.947218,2047.839069,703974.0,2914.0,7089762.0
2026-06-30 14:57:00,MA,MA609,2041.947218,2042.788911,2041.105525,2042.788911,2047.839069,703547.0,2046.0,4977918.0
2026-06-30 14:58:00,MA,MA609,2041.947218,2043.630604,2041.105525,2042.788911,2047.839069,702203.0,4478.0,10894974.0
2026-06-30 14:59:00,MA,MA609,2042.788911,2043.630604,2041.947218,2043.630604,2047.839069,700024.0,6224.0,15142992.0

In [10]:
#### 对比公式
def rolling_compare(research_data, bench_data, name, window):
    common = (research_data[['trade_time', 'code', name
                             ]].merge(bench_data[['trade_time', 'code', name]],
                                      on=["trade_time", "code"],
                                      suffixes=("_research", "_bench")))
    common["rolling_corr"] = (
        common["{}_research".format(name)].rolling(window).corr(
            common["{}_bench".format(name)]))
    return common

### 成交量 价格对比

In [11]:
volume_common = rolling_compare(
    research_data=research_data, 
    bench_data=bench_data, 
    name = 'volume', window=5)
volume_common.tail()

              trade_time code  volume_research  volume_bench  rolling_corr
7000 2026-06-30 14:55:00   MA           2690.0        2442.0      0.851140
7001 2026-06-30 14:56:00   MA           2914.0        2937.0      0.962226
7002 2026-06-30 14:57:00   MA           2046.0        2108.0      0.992383
7003 2026-06-30 14:58:00   MA           4478.0        4555.0      0.996271
7004 2026-06-30 14:59:00   MA           6224.0        6045.0      0.996166

In [12]:
volume_common[volume_common['rolling_corr'] < 0.9]

              trade_time code  volume_research  volume_bench  rolling_corr
104  2026-06-01 10:59:00   MA           1155.0        1527.0      0.864708
105  2026-06-01 11:00:00   MA           1539.0        1155.0      0.631658
106  2026-06-01 11:01:00   MA           1771.0        1762.0      0.732164
107  2026-06-01 11:02:00   MA            970.0         978.0      0.771158
108  2026-06-01 11:03:00   MA            700.0         766.0      0.794197
...                  ...  ...              ...           ...           ...
6996 2026-06-30 14:51:00   MA           4242.0        5470.0      0.849466
6997 2026-06-30 14:52:00   MA           6760.0        5693.0      0.867479
6998 2026-06-30 14:53:00   MA           3877.0        3668.0      0.875149
6999 2026-06-30 14:54:00   MA           5540.0        5776.0      0.758903
7000 2026-06-30 14:55:00   MA           2690.0        2442.0      0.851140

[260 rows x 5 columns]

### 持仓量 对比

In [13]:
openint_common = rolling_compare(
    research_data=research_data, 
    bench_data=bench_data, 
    name = 'openint', window=5)
openint_common.tail()

              trade_time code  openint_research  openint_bench  rolling_corr
7000 2026-06-30 14:55:00   MA          704384.0       704381.0      0.998025
7001 2026-06-30 14:56:00   MA          703974.0       703975.0      0.999980
7002 2026-06-30 14:57:00   MA          703547.0       703562.0      0.999971
7003 2026-06-30 14:58:00   MA          702203.0       702061.0      0.999152
7004 2026-06-30 14:59:00   MA          700024.0       700024.0      0.999357

In [14]:
openint_common[openint_common['rolling_corr'] < 0.9]

              trade_time code  openint_research  openint_bench  rolling_corr
265  2026-06-01 21:40:00   MA          741569.0       741572.0      0.881542
266  2026-06-01 21:41:00   MA          741151.0       741092.0      0.760442
267  2026-06-01 21:42:00   MA          741308.0       741281.0      0.833267
268  2026-06-01 21:43:00   MA          741738.0       741572.0      0.737680
448  2026-06-02 10:58:00   MA          721210.0       721218.0      0.879561
...                  ...  ...               ...            ...           ...
6819 2026-06-30 09:39:00   MA          691686.0       691891.0      0.749438
6820 2026-06-30 09:40:00   MA          691802.0       691797.0      0.616549
6821 2026-06-30 09:41:00   MA          691695.0       691760.0      0.746512
6822 2026-06-30 09:42:00   MA          691692.0       691692.0      0.432235
6823 2026-06-30 09:43:00   MA          691974.0       691972.0      0.709936

[154 rows x 5 columns]

### vwap 价格对比

In [15]:
vwap_common = rolling_compare(
    research_data=research_data, 
    bench_data=bench_data, 
    name = 'vwap', window=5)
vwap_common.head()

           trade_time code  vwap_research   vwap_bench  rolling_corr
0 2026-06-01 09:00:00   MA    2362.666030  2365.023003           NaN
1 2026-06-01 09:01:00   MA    2393.949257  2372.426099           NaN
2 2026-06-01 09:02:00   MA    2346.640084  2371.365184           NaN
3 2026-06-01 09:03:00   MA    2391.731497  2369.185221           NaN
4 2026-06-01 09:04:00   MA    2347.481777  2372.056346     -0.004288

In [17]:
vwap_common[vwap_common['rolling_corr'] < 0.9]

              trade_time code  vwap_research   vwap_bench  rolling_corr
4    2026-06-01 09:04:00   MA    2347.481777  2372.056346     -0.004288
5    2026-06-01 09:05:00   MA    2413.529664  2368.314875     -0.640417
6    2026-06-01 09:06:00   MA    2348.323470  2367.668925     -0.500431
7    2026-06-01 09:07:00   MA    2348.323470  2370.932063     -0.475268
8    2026-06-01 09:08:00   MA    2384.958485  2374.317107     -0.061093
...                  ...  ...            ...          ...           ...
6981 2026-06-30 14:36:00   MA    2047.839069  2031.688778     -0.601292
6982 2026-06-30 14:37:00   MA    2047.839069  2031.654481     -0.626844
6983 2026-06-30 14:38:00   MA    2047.839069  2031.659542     -0.844084
6985 2026-06-30 14:40:00   MA    2047.839069  2032.615865          -inf
7004 2026-06-30 14:59:00   MA    2047.839069  2049.420394          -inf

[3888 rows x 5 columns]

### 收盘 价格对比

In [13]:
close_common = rolling_compare(
    research_data=research_data, 
    bench_data=bench_data, 
    name = 'close', window=5)
close_common.head()

           trade_time code  close_research  close_bench  rolling_corr
0 2025-01-02 09:00:00   MA     2152.085157  2152.085157           NaN
1 2025-01-02 09:01:00   MA     2148.130572  2148.921489           NaN
2 2025-01-02 09:02:00   MA     2152.085157  2151.294240           NaN
3 2025-01-02 09:03:00   MA     2148.130572  2147.339655           NaN
4 2025-01-02 09:04:00   MA     2144.966904  2144.175987       0.97526

In [15]:
close_common[close_common['rolling_corr'] < 0.9]

               trade_time code  close_research  close_bench  rolling_corr
22    2025-01-02 09:22:00   MA     2142.594153  2143.385070      0.896421
25    2025-01-02 09:25:00   MA     2146.548738  2148.130572      0.892783
27    2025-01-02 09:27:00   MA     2148.130572  2147.339655      0.505650
28    2025-01-02 09:28:00   MA     2147.339655  2148.130572      0.071429
29    2025-01-02 09:29:00   MA     2147.339655  2147.339655      0.071429
...                   ...  ...             ...          ...           ...
72607 2025-12-31 14:55:00   MA     1682.491352  1683.250599      0.620174
72608 2025-12-31 14:56:00   MA     1682.491352  1681.732105      0.133631
72609 2025-12-31 14:57:00   MA     1681.732105  1681.732105      0.422577
72610 2025-12-31 14:58:00   MA     1681.732105  1681.732105      0.612372
72611 2025-12-31 14:59:00   MA     1682.491352  1682.491352      0.612372

[47223 rows x 5 columns]

               trade_time code  volume_research  volume_bench  rolling_corr
72607 2025-12-31 14:55:00   MA           2953.0        2926.0      0.995880
72608 2025-12-31 14:56:00   MA           2108.0        2119.0      0.996304
72609 2025-12-31 14:57:00   MA           2001.0        1959.0      0.994698
72610 2025-12-31 14:58:00   MA           6030.0        6199.0      0.999399
72611 2025-12-31 14:59:00   MA           7148.0        6915.0      0.998225

In [17]:
volume_common[volume_common['rolling_corr'] < 0.9]

               trade_time code  volume_research  volume_bench  rolling_corr
36    2025-01-02 09:36:00   MA           1818.0        1913.0      0.875780
68    2025-01-02 10:08:00   MA           1543.0        1539.0      0.894884
69    2025-01-02 10:09:00   MA           1285.0        1288.0      0.622639
98    2025-01-02 10:53:00   MA           1026.0        1285.0      0.899079
99    2025-01-02 10:54:00   MA            735.0         476.0      0.895252
...                   ...  ...              ...           ...           ...
72551 2025-12-31 13:59:00   MA           1916.0        1655.0      0.802108
72552 2025-12-31 14:00:00   MA           1421.0        2198.0     -0.605718
72553 2025-12-31 14:01:00   MA           1733.0         988.0     -0.569551
72554 2025-12-31 14:02:00   MA           1112.0        1082.0      0.125093
72555 2025-12-31 14:03:00   MA           2519.0        2517.0      0.602925

[25225 rows x 5 columns]

### 收益率对比

In [18]:
research_chg = create_chg(market_data = research_data, name='vwap')
bench_chg = create_chg(market_data = bench_data, name='vwap')

In [19]:
pct_common = rolling_compare(
    research_data=research_chg, 
    bench_data=bench_chg, 
    name = 'chg_pct', window=5)
pct_common.head()

           trade_time code  chg_pct_research  chg_pct_bench  rolling_corr
0 2025-01-02 09:00:00   MA          0.000000      -0.000593           NaN
1 2025-01-02 09:01:00   MA          0.000000      -0.000047           NaN
2 2025-01-02 09:02:00   MA          0.000000      -0.001570           NaN
3 2025-01-02 09:03:00   MA         -0.002848      -0.001778           NaN
4 2025-01-02 09:04:00   MA         -0.001592      -0.000903      0.588045

In [20]:
# diff = '2025-01-02 11:28:00'

In [21]:
# bench_data[bench_data['trade_time'] <=diff].tail(7)

In [22]:
# research_data[research_data['trade_time'] <=diff].tail(7)