#### 投研自行合成数据和交易自行合成数据对比

In [1]:
import os
from dotenv import load_dotenv

load_dotenv()
import pandas as pd

In [2]:
from config.contract import TRADING_TIME_MAPPING
from kdutils.data import fetch_local_market1, fetch_trader_market1
from lib.attr001.ftd001 import filter_trading_time
from lib.ret001 import create_chg, create_yields

/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:11: UserWarning: if use distributed calculating, please configure MQ_URL
  warnings.warn('if use distributed calculating, please configure MQ_URL')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:15: UserWarning: if use distributed calculating, please configure NTN_URL
  warnings.warn('if use distributed calculating, please configure NTN_URL')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:19: UserWarning: if use memory database, please configure KN_MG
  warnings.warn('if use memory database, please configure KN_MG')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:27: UserWarning: if use trader, please configure ATL_URL
  warnings.warn('if use trader, please configure ATL_URL')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:31: UserWarning: if use trader, please configure IREY_URL
  warnings.warn('if use trader, please configure IREY_URL')

In [3]:
code = 'RB'
trading_sessions = TRADING_TIME_MAPPING[code]
begin_date = '2026-05-01'
end_data = '2026-07-01'

In [4]:
keep_columns = ['trade_time','code','symbol', 'open','high','low','close','vwap','volume','openint']

In [5]:
research_data = fetch_local_market1(base_path=os.environ['BAR_FUT_DIRS'],
                                       begin_date=begin_date,
                                       end_date=end_data,
                                       keep_symbol=True,
                                       codes=[code])
research_data = research_data[keep_columns]
research_data['trade_time'] = pd.to_datetime(research_data['trade_time'])
research_data = research_data.set_index(['trade_time','code'])
research_data = filter_trading_time(data=research_data, trading_sessions=trading_sessions).sort_values(by=['trade_time','code'])

/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260506/rb2610_20260506.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260507/rb2610_20260507.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260508/rb2610_20260508.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260511/rb2610_20260511.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260512/rb2610_20260512.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260513/rb2610_20260513.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260514/rb2610_20260514.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260515/rb2610_20260515.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260518/rb2610_20260518.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260519/rb2610_20260519.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260520/rb2610_20260520.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260521/rb2610_20260521.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260522/rb2610_20260522.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260525/rb2610_20260525.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260526/rb2610_20260526.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260527/rb2610_20260527.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260528/rb2610_20260528.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260529/rb2610_20260529.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260601/rb2610_20260601.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260602/rb2610_20260602.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260603/rb2610_20260603.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260604/rb2610_20260604.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260605/rb2610_20260605.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260608/rb2610_20260608.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260609/rb2610_20260609.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260610/rb2610_20260610.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260611/rb2610_20260611.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260612/rb2610_20260612.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260615/rb2610_20260615.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260616/rb2610_20260616.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260617/rb2610_20260617.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260618/rb2610_20260618.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260622/rb2610_20260622.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260623/rb2610_20260623.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260624/rb2610_20260624.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260625/rb2610_20260625.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260626/rb2610_20260626.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260629/rb2610_20260629.feather
/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260630/rb2610_20260630.feather
 file does not exist: /workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260701/rb2610_20260701.feather

In [6]:
research_data.head()

,trade_time,code,symbol,open,high,low,close,vwap,volume,openint
0,2026-05-06 09:00:00,RB,rb2610,3877.948116,3877.948116,3867.135993,3874.344075,3872.814421,23086.0,1886557.0
1,2026-05-06 09:01:00,RB,rb2610,3875.545422,3879.149463,3874.344075,3876.746769,3877.258644,11946.0,1889276.0
2,2026-05-06 09:02:00,RB,rb2610,3876.746769,3880.350810,3876.746769,3880.350810,3878.857846,13570.0,1895028.0
3,2026-05-06 09:03:00,RB,rb2610,3880.350810,3881.552157,3879.149463,3880.350810,3880.381374,11163.0,1898630.0
4,2026-05-06 09:04:00,RB,rb2610,3880.350810,3880.350810,3875.545422,3877.948116,3877.564763,6863.0,1898959.0

In [7]:
trader_data = fetch_trader_market1(begin_time=begin_date,
                                     end_time=end_data,
                                     code=code)
trader_data = trader_data[keep_columns]
trader_data['trade_time'] = pd.to_datetime(trader_data['trade_time'])
trader_data = trader_data.set_index(['trade_time','code'])
trader_data = filter_trading_time(data=trader_data, trading_sessions=trading_sessions).sort_values(by=['trade_time','code'])

Pandas(Index=0, symbol='rb2610', start_date=Timestamp('2026-05-06 00:00:00'), end_date=Timestamp('2026-07-01 00:00:00'))

In [8]:
trader_data.head()

,trade_time,code,symbol,open,high,low,close,vwap,volume,openint
0,2026-05-06 09:40:00,RB,rb2610,3894.766974,3897.169668,3894.766974,3895.968321,3235.231164,31348539,1946718.0
1,2026-05-06 09:41:00,RB,rb2610,3895.968321,3899.572362,3895.968321,3898.371015,3235.340873,31488648,1949246.0
2,2026-05-06 09:42:00,RB,rb2610,3898.371015,3899.572362,3897.169668,3899.572362,3235.502093,32290583,1949791.0
3,2026-05-06 09:43:00,RB,rb2610,3899.572362,3899.572362,3897.169668,3899.572362,3235.573366,32531234,1950545.0
4,2026-05-06 09:44:00,RB,rb2610,3898.371015,3899.572362,3898.371015,3898.371015,3235.646208,32776452,1951529.0

In [13]:
#### 对比公式
def rolling_compare(research_data, trader_data, name, window):
    common = (research_data[['trade_time', 'code', name
                             ]].merge(trader_data[['trade_time', 'code', name]],
                                      on=["trade_time", "code"],
                                      suffixes=("_research", "_trader")))
    common["rolling_corr"] = (
        common["{}_research".format(name)].rolling(window).corr(
            common["{}_trader".format(name)]))
    return common

### vwap 价格对比

In [14]:
vwap_common = rolling_compare(
    research_data=research_data, 
    trader_data=trader_data, 
    name = 'vwap', window=5)
vwap_common.head()

           trade_time code  vwap_research  vwap_trader  rolling_corr
0 2026-05-06 09:40:00   RB    3895.525111  3235.231164           NaN
1 2026-05-06 09:41:00   RB    3897.863540  3235.340873           NaN
2 2026-05-06 09:42:00   RB    3898.710504  3235.502093           NaN
3 2026-05-06 09:43:00   RB    3898.619662  3235.573366           NaN
4 2026-05-06 09:44:00   RB    3898.970287  3235.646208      0.899042

In [15]:
vwap_common[vwap_common['rolling_corr'] < 0.9]

               trade_time code  vwap_research  vwap_trader  rolling_corr
4     2026-05-06 09:44:00   RB    3898.970287  3235.646208      0.899042
5     2026-05-06 09:45:00   RB    3898.547635  3235.739415      0.715367
6     2026-05-06 09:46:00   RB    3897.438270  3235.807897     -0.702490
7     2026-05-06 09:47:00   RB    3896.168546  3235.863743     -0.854760
8     2026-05-06 09:48:00   RB    3896.426329  3235.941163     -0.933772
...                   ...  ...            ...          ...           ...
12358 2026-06-30 11:30:00   RB    3703.752801  3082.245798      0.362519
12359 2026-06-30 13:31:00   RB    3702.389734  3081.865385      0.670093
12360 2026-06-30 13:32:00   RB    3702.498895  3081.956250      0.736351
12361 2026-06-30 13:33:00   RB    3702.892577  3082.283951      0.692201
12362 2026-06-30 13:34:00   RB    3703.907814  3083.129032      0.818841

[2568 rows x 5 columns]

### 收盘 价格对比

In [16]:
close_common = rolling_compare(
    research_data=research_data, 
    trader_data=trader_data, 
    name = 'close', window=5)
close_common.head()

           trade_time code  close_research  close_trader  rolling_corr
0 2026-05-06 09:40:00   RB     3895.968321   3895.968321           NaN
1 2026-05-06 09:41:00   RB     3898.371015   3898.371015           NaN
2 2026-05-06 09:42:00   RB     3899.572362   3899.572362           NaN
3 2026-05-06 09:43:00   RB     3899.572362   3899.572362           NaN
4 2026-05-06 09:44:00   RB     3898.371015   3898.371015           1.0

In [17]:
close_common[close_common['rolling_corr'] < 0.9]

               trade_time code  close_research  close_trader  rolling_corr
647   2026-05-08 11:30:00   RB     3935.612772   3938.015466  7.453560e-01
648   2026-05-08 13:31:00   RB     3939.216813   3939.216813  8.427010e-01
649   2026-05-08 13:32:00   RB     3939.216813   3939.216813  8.827348e-01
650   2026-05-08 13:33:00   RB     3939.216813   3939.216813  8.885233e-01
651   2026-05-08 13:34:00   RB     3938.015466   3938.015466  8.401681e-01
983   2026-05-11 11:30:00   RB     3954.834324   3956.035671  6.123724e-01
1671  2026-05-13 11:30:00   RB     3901.975056   3905.579097  5.562939e-01
1672  2026-05-13 13:31:00   RB     3904.377750   3904.377750 -2.857143e-01
1673  2026-05-13 13:32:00   RB     3904.377750   3904.377750 -2.857143e-01
1674  2026-05-13 13:33:00   RB     3904.377750   3904.377750 -3.952847e-01
1675  2026-05-13 13:34:00   RB     3904.377750   3904.377750 -1.000000e+00
2016  2026-05-14 11:30:00   RB     3894.766974   3905.579097  3.521014e-01
2017  2026-05-14 13:31:00   RB     3904.377750   3904.377750  5.178806e-01
2018  2026-05-14 13:32:00   RB     3906.780444   3906.780444  6.440821e-01
2019  2026-05-14 13:33:00   RB     3910.384485   3910.384485  7.388456e-01
2020  2026-05-14 13:34:00   RB     3906.780444   3906.780444  6.247786e-01
2361  2026-05-15 11:30:00   RB     3892.364280   3888.760239 -2.857143e-01
2362  2026-05-15 13:31:00   RB     3886.357545   3886.357545  7.301095e-01
2363  2026-05-15 13:32:00   RB     3887.558892   3887.558892  7.864587e-01
2364  2026-05-15 13:33:00   RB     3888.760239   3888.760239  7.640509e-01
2365  2026-05-15 13:34:00   RB     3889.961586   3889.961586  7.295372e-01
2578  2026-05-18 11:30:00   RB     3863.531952   3862.330605  7.905694e-01
2580  2026-05-18 13:32:00   RB     3863.531952   3863.531952  6.123724e-01
2581  2026-05-18 13:33:00   RB     3863.531952   3863.531952  6.666667e-01
2582  2026-05-18 13:34:00   RB     3864.733299   3864.733299  8.451543e-01
4651  2026-05-27 11:30:00   RB     3778.236315   3781.840356 -2.500000e-01
4652  2026-05-27 13:31:00   RB     3784.243050   3784.243050  7.836446e-01
5343  2026-05-29 11:30:00   RB     3801.061908   3805.867296  7.453560e-01
5344  2026-05-29 13:31:00   RB     3804.665949   3804.665949  7.687422e-01
5345  2026-05-29 13:32:00   RB     3803.464602   3803.464602  6.816229e-01
5346  2026-05-29 13:33:00   RB     3802.263255   3802.263255  2.425356e-01
5347  2026-05-29 13:34:00   RB     3804.665949   3804.665949 -6.726728e-02
6034  2026-06-02 11:30:00   RB     3814.276725   3811.874031  6.123724e-01
6610  2026-06-04 13:33:00   RB     3803.464602   3803.464602  8.918919e-01
6611  2026-06-04 13:34:00   RB     3805.867296   3805.867296  8.912685e-01
7986  2026-06-10 11:30:00   RB     3787.847091   3785.444397  8.427010e-01
7987  2026-06-10 13:31:00   RB     3785.444397   3785.444397  7.484552e-01
7988  2026-06-10 13:32:00   RB     3786.645744   3786.645744  7.399401e-01
7989  2026-06-10 13:33:00   RB     3786.645744   3786.645744  7.161149e-01
7990  2026-06-10 13:34:00   RB     3786.645744   3786.645744 -4.165408e-09
8682  2026-06-12 11:30:00   RB     3827.491542   3823.887501  8.385255e-01
8683  2026-06-12 13:31:00   RB     3821.484807   3821.484807  8.685990e-01
8685  2026-06-12 13:33:00   RB     3821.484807   3821.484807  8.946301e-01
10071 2026-06-18 11:30:00   RB     3757.813416   3762.618804  6.163156e-01
10072 2026-06-18 13:31:00   RB     3765.021498   3765.021498  8.159417e-01
10073 2026-06-18 13:32:00   RB     3762.618804   3762.618804  7.905694e-01
10074 2026-06-18 13:33:00   RB     3762.618804   3762.618804  7.484552e-01
10075 2026-06-18 13:34:00   RB     3762.618804   3762.618804  6.123724e-01
10991 2026-06-24 11:30:00   RB     3738.591864   3743.397252  4.588315e-01
10992 2026-06-24 13:31:00   RB     3744.598599   3744.598599  7.184212e-01
10993 2026-06-24 13:32:00   RB     3744.598599   3744.598599  7.758802e-01
10994 2026-06-24 13:33:00   RB     3743.397252   3743.397252  7.265960e-01
10995 2026-06-24 13:34:00   RB     3744.598599   3744.598599  7.579367e-01
12358 2026-06-30 11:30:00   RB     3703.752801   3702.551454  6.123724e-01
12359 2026-06-30 13:31:00   RB     3701.350107   3701.350107  8.685990e-01
12360 2026-06-30 13:32:00   RB     3703.752801   3703.752801  8.685990e-01
12361 2026-06-30 13:33:00   RB     3702.551454   3702.551454  8.451543e-01
12362 2026-06-30 13:34:00   RB     3703.752801   3703.752801  8.685990e-01

### 成交量 对比

In [18]:
volume_common = rolling_compare(
    research_data=research_data, 
    trader_data=trader_data, 
    name = 'volume', window=5)
volume_common.tail()

               trade_time code  volume_research  volume_trader  rolling_corr
12444 2026-06-30 14:56:00   RB           2486.0           2486      0.999999
12445 2026-06-30 14:57:00   RB           5209.0           5209      0.999999
12446 2026-06-30 14:58:00   RB           4851.0           4851      0.999999
12447 2026-06-30 14:59:00   RB           6523.0           6523      0.999999
12448 2026-06-30 15:00:00   RB              8.0              8      1.000000

In [19]:
volume_common[volume_common['rolling_corr'] < 0.9]

               trade_time code  volume_research  volume_trader  rolling_corr
4     2026-05-06 09:44:00   RB           2143.0       32776452     -0.547942
5     2026-05-06 09:45:00   RB           2163.0       33090794     -0.896823
6     2026-05-06 09:46:00   RB           2366.0       33349659     -0.112279
7     2026-05-06 09:47:00   RB           2910.0       33586372      0.762785
8     2026-05-06 09:48:00   RB           2602.0       33953540      0.772654
...                   ...  ...              ...            ...           ...
12358 2026-06-30 11:30:00   RB              1.0           2856     -0.488329
12359 2026-06-30 13:31:00   RB           1040.0           1040     -0.516749
12360 2026-06-30 13:32:00   RB           1120.0           1120     -0.496689
12361 2026-06-30 13:33:00   RB           1539.0           1539     -0.832397
12362 2026-06-30 13:34:00   RB           1953.0           1953     -0.507525

[2974 rows x 5 columns]

### 持仓量 对比

In [24]:
openint_common = rolling_compare(
    research_data=research_data, 
    trader_data=trader_data, 
    name = 'openint', window=5)
openint_common.tail()

               trade_time code  openint_research  openint_trader  rolling_corr
12444 2026-06-30 14:56:00   RB         1973960.0       1973960.0           1.0
12445 2026-06-30 14:57:00   RB         1974131.0       1974131.0           1.0
12446 2026-06-30 14:58:00   RB         1972893.0       1972893.0           1.0
12447 2026-06-30 14:59:00   RB         1971778.0       1971778.0           1.0
12448 2026-06-30 15:00:00   RB         1971770.0       1971770.0           1.0

In [25]:
openint_common[openint_common['rolling_corr'] < 0.9]

               trade_time code  openint_research  openint_trader  rolling_corr
647   2026-05-08 11:30:00   RB         2152297.0       2150827.0      0.431673
648   2026-05-08 13:31:00   RB         2150852.0       2150852.0      0.611233
649   2026-05-08 13:32:00   RB         2151027.0       2151027.0      0.632199
650   2026-05-08 13:33:00   RB         2151997.0       2151997.0      0.556963
651   2026-05-08 13:34:00   RB         2152083.0       2152083.0      0.481949
...                   ...  ...               ...             ...           ...
10995 2026-06-24 13:34:00   RB         1828823.0       1828823.0      0.713338
12033 2026-06-29 13:31:00   RB         1934644.0       1934644.0      0.860105
12034 2026-06-29 13:32:00   RB         1934421.0       1934421.0      0.829796
12035 2026-06-29 13:33:00   RB         1934359.0       1934359.0      0.773439
12036 2026-06-29 13:34:00   RB         1934362.0       1934362.0      0.875695

[62 rows x 5 columns]

### 收益率对比

In [20]:
research_chg = create_chg(market_data = research_data, name='vwap')
trader_chg = create_chg(market_data = trader_data, name='vwap')

In [22]:
pct_common = rolling_compare(
    research_data=research_chg, 
    trader_data=trader_chg, 
    name = 'chg_pct', window=5)
pct_common.head()

           trade_time code  chg_pct_research  chg_pct_trader  rolling_corr
0 2026-05-06 09:40:00   RB          0.000217        0.000050           NaN
1 2026-05-06 09:41:00   RB         -0.000023        0.000022           NaN
2 2026-05-06 09:42:00   RB          0.000090        0.000023           NaN
3 2026-05-06 09:43:00   RB         -0.000108        0.000029           NaN
4 2026-05-06 09:44:00   RB         -0.000285        0.000021      0.685148