In [1]:
import pandas as pd

In [2]:
filename = "/workspace/data/dev/kd/intelkit/records/raw_data/cn_futures/20260511/rb2610_20260511.feather"

In [3]:
pd.read_feather(filename)

,vt_symbol,symbol,exchange,open,high,low,close,date,time,datetime,volume,value,open_interest,vwap
0,rb2610.XSGE,rb2610,XSGE,3262.0,3262.0,3262.0,3262.0,2026-05-08,20:59:00,2026-05-08 20:59:00,0.0,0.0,2144276.0,3262.000000
1,rb2610.XSGE,rb2610,XSGE,3262.0,3270.0,3262.0,3268.0,2026-05-08,21:00:00,2026-05-08 21:00:00,15487.0,505951620.0,2144863.0,3266.944018
2,rb2610.XSGE,rb2610,XSGE,3268.0,3268.0,3264.0,3265.0,2026-05-08,21:01:00,2026-05-08 21:01:00,6763.0,220886780.0,2144970.0,3266.106462
3,rb2610.XSGE,rb2610,XSGE,3265.0,3266.0,3263.0,3264.0,2026-05-08,21:02:00,2026-05-08 21:02:00,4350.0,141990090.0,2145101.0,3264.140000
4,rb2610.XSGE,rb2610,XSGE,3264.0,3264.0,3260.0,3260.0,2026-05-08,21:03:00,2026-05-08 21:03:00,10187.0,332217470.0,2144122.0,3261.190439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,rb2610.XSGE,rb2610,XSGE,3286.0,3287.0,3285.0,3286.0,2026-05-11,14:57:00,2026-05-11 14:57:00,2351.0,77253500.0,2173640.0,3285.984687
347,rb2610.XSGE,rb2610,XSGE,3286.0,3286.0,3285.0,3285.0,2026-05-11,14:58:00,2026-05-11 14:58:00,2193.0,72046410.0,2173645.0,3285.290014
348,rb2610.XSGE,rb2610,XSGE,3286.0,3287.0,3285.0,3286.0,2026-05-11,14:59:00,2026-05-11 14:59:00,6087.0,199994850.0,2172557.0,3285.606210
349,rb2610.XSGE,rb2610,XSGE,3286.0,3286.0,3286.0,3286.0,2026-05-11,15:00:00,2026-05-11 15:00:00,6.0,197130.0,2172556.0,3285.500000
350,rb2610.XSGE,rb2610,XSGE,3286.0,3286.0,3286.0,3286.0,2026-05-11,15:21:00,2026-05-11 15:21:00,0.0,0.0,2172556.0,3286.000000

In [4]:
from lib.agg001.builder import minute_bars
from lib.agg001.builder1 import minute_bars as minute_bars1
from lib.agg001.builder2 import minute_bars as minute_bars2
import datetime

In [5]:
file_path = '/workspace/data/fut_tick/7050707549_-/2026/202605/20260518/rb2610_20260518.csv'
multiplier = 10
night_session_start = datetime.time(20, 0, 0)

In [6]:
dt0 = minute_bars(csv_path=file_path, multiplier=multiplier,
            night_session_start=night_session_start, 
            exchange='SHFE')

In [7]:
dt1 = minute_bars1(csv_path=file_path, multiplier=multiplier,
            night_session_start=night_session_start, 
            exchange='SHFE')

In [8]:
dt2 = minute_bars2(csv_path=file_path, multiplier=multiplier,
            night_session_start=night_session_start, 
            exchange='SHFE')

In [10]:
dt2.reset_index(drop=True).head()

,vt_symbol,symbol,exchange,open,high,low,close,date,time,datetime,volume,value,open_interest,vwap
0,rb2610.SHFE,rb2610,SHFE,3232.0,3232.0,3232.0,3232.0,2026-05-17,20:59:00,2026-05-17 20:59:00,0.0,0.0,2019856.0,3232.000000
1,rb2610.SHFE,rb2610,SHFE,3231.0,3236.0,3229.0,3235.0,2026-05-17,21:00:00,2026-05-17 21:00:00,15894.0,513888670.0,2017912.0,3233.224298
2,rb2610.SHFE,rb2610,SHFE,3235.0,3235.0,3228.0,3228.0,2026-05-17,21:01:00,2026-05-17 21:01:00,9455.0,305541190.0,2017974.0,3231.530301
3,rb2610.SHFE,rb2610,SHFE,3228.0,3230.0,3227.0,3230.0,2026-05-17,21:02:00,2026-05-17 21:02:00,8947.0,288826500.0,2016811.0,3228.193808
4,rb2610.SHFE,rb2610,SHFE,3229.0,3232.0,3229.0,3232.0,2026-05-17,21:03:00,2026-05-17 21:03:00,6792.0,219401370.0,2018136.0,3230.291078

In [11]:
dt1.reset_index(drop=True).head()

,vt_symbol,symbol,exchange,open,high,low,close,date,time,datetime,volume,value,open_interest,vwap
0,rb2610.SHFE,rb2610,SHFE,3232.0,3232.0,3232.0,3232.0,2026-05-17,20:59:00,2026-05-17 20:59:00,0.0,0.0,2019856.0,3232.000000
1,rb2610.SHFE,rb2610,SHFE,3231.0,3236.0,3229.0,3235.0,2026-05-17,21:00:00,2026-05-17 21:00:00,15894.0,513888670.0,2017912.0,3233.224298
2,rb2610.SHFE,rb2610,SHFE,3235.0,3235.0,3228.0,3228.0,2026-05-17,21:01:00,2026-05-17 21:01:00,9455.0,305541190.0,2017974.0,3231.530301
3,rb2610.SHFE,rb2610,SHFE,3228.0,3230.0,3227.0,3230.0,2026-05-17,21:02:00,2026-05-17 21:02:00,8947.0,288826500.0,2016811.0,3228.193808
4,rb2610.SHFE,rb2610,SHFE,3229.0,3232.0,3229.0,3232.0,2026-05-17,21:03:00,2026-05-17 21:03:00,6792.0,219401370.0,2018136.0,3230.291078

In [9]:
import pandas as pd
import numpy as np

def compare_frames(df_old, df_new, key_cols=None, float_tol=1e-9):
    left = df_old.copy()
    right = df_new.copy()

    if key_cols is None:
        key_cols = ["datetime", "vt_symbol"]

    left = left.sort_values(key_cols).reset_index(drop=True)
    right = right.sort_values(key_cols).reset_index(drop=True)

    result = {}

    # 1. 形状和列是否一致
    result["shape_equal"] = left.shape == right.shape
    result["columns_equal"] = list(left.columns) == list(right.columns)

    common_cols = [c for c in left.columns if c in right.columns]

    # 2. 每列是否一致
    column_summary = []
    diff_rows = []

    for col in common_cols:
        s1 = left[col]
        s2 = right[col]

        if pd.api.types.is_numeric_dtype(s1) and pd.api.types.is_numeric_dtype(s2):
            equal_mask = np.isclose(s1.astype(float), s2.astype(float), atol=float_tol, rtol=0, equal_nan=True)
        else:
            equal_mask = s1.fillna("__NA__").eq(s2.fillna("__NA__"))

        mismatch_count = int((~equal_mask).sum())

        column_summary.append({
            "column": col,
            "equal": mismatch_count == 0,
            "mismatch_count": mismatch_count,
        })

        if mismatch_count > 0:
            idx = np.where(~equal_mask)[0]
            for i in idx[:20]:   # 每列最多展示前20条
                row = {"row": int(i), "column": col, "old": s1.iloc[i], "new": s2.iloc[i]}
                for k in key_cols:
                    row[k] = left.iloc[i][k]
                diff_rows.append(row)

    result["column_summary"] = pd.DataFrame(column_summary)
    result["diff_rows"] = pd.DataFrame(diff_rows)

    return result

In [13]:
cmp = compare_frames(dt0.reset_index(drop=True), dt2.reset_index(drop=True))
cmp

{'shape_equal': True,
 'columns_equal': True,
 'column_summary':            column  equal  mismatch_count
 0       vt_symbol   True               0
 1          symbol   True               0
 2        exchange   True               0
 3            open   True               0
 4            high   True               0
 5             low   True               0
 6           close   True               0
 7            date  False             122
 8            time   True               0
 9        datetime  False             122
 10         volume   True               0
 11          value   True               0
 12  open_interest   True               0
 13           vwap   True               0,
 'diff_rows':     row    column                  old                  new  \
 0     0      date           2026-05-15           2026-05-17
 1     1      date           2026-05-15           2026-05-17
 2     2      date           2026-05-15           2026-05-17
 3     3      date           2026-05-15           2026-05-17
 4     4      date           2026-05-15           2026-05-17
 5     5      date           2026-05-15           2026-05-17
 6     6      date           2026-05-15           2026-05-17
 7     7      date           2026-05-15           2026-05-17
 8     8      date           2026-05-15           2026-05-17
 9     9      date           2026-05-15           2026-05-17
 10   10      date           2026-05-15           2026-05-17
 11   11      date           2026-05-15           2026-05-17
 12   12      date           2026-05-15           2026-05-17
 13   13      date           2026-05-15           2026-05-17
 14   14      date           2026-05-15           2026-05-17
 15   15      date           2026-05-15           2026-05-17
 16   16      date           2026-05-15           2026-05-17
 17   17      date           2026-05-15           2026-05-17
 18   18      date           2026-05-15           2026-05-17
 19   19      date           2026-05-15           2026-05-17
 20    0  datetime  2026-05-15 20:59:00  2026-05-17 20:59:00
 21    1  datetime  2026-05-15 21:00:00  2026-05-17 21:00:00
 22    2  datetime  2026-05-15 21:01:00  2026-05-17 21:01:00
 23    3  datetime  2026-05-15 21:02:00  2026-05-17 21:02:00
 24    4  datetime  2026-05-15 21:03:00  2026-05-17 21:03:00
 25    5  datetime  2026-05-15 21:04:00  2026-05-17 21:04:00
 26    6  datetime  2026-05-15 21:05:00  2026-05-17 21:05:00
 27    7  datetime  2026-05-15 21:06:00  2026-05-17 21:06:00
 28    8  datetime  2026-05-15 21:07:00  2026-05-17 21:07:00
 29    9  datetime  2026-05-15 21:08:00  2026-05-17 21:08:00
 30   10  datetime  2026-05-15 21:09:00  2026-05-17 21:09:00
 31   11  datetime  2026-05-15 21:10:00  2026-05-17 21:10:00
 32   12  datetime  2026-05-15 21:11:00  2026-05-17 21:11:00
 33   13  datetime  2026-05-15 21:12:00  2026-05-17 21:12:00
 34   14  datetime  2026-05-15 21:13:00  2026-05-17 21:13:00
 35   15  datetime  2026-05-15 21:14:00  2026-05-17 21:14:00
 36   16  datetime  2026-05-15 21:15:00  2026-05-17 21:15:00
 37   17  datetime  2026-05-15 21:16:00  2026-05-17 21:16:00
 38   18  datetime  2026-05-15 21:17:00  2026-05-17 21:17:00
 39   19  datetime  2026-05-15 21:18:00  2026-05-17 21:18:00

                datetime    vt_symbol
 0   2026-05-15 20:59:00  rb2610.SHFE
 1   2026-05-15 21:00:00  rb2610.SHFE
 2   2026-05-15 21:01:00  rb2610.SHFE
 3   2026-05-15 21:02:00  rb2610.SHFE
 4   2026-05-15 21:03:00  rb2610.SHFE
 5   2026-05-15 21:04:00  rb2610.SHFE
 6   2026-05-15 21:05:00  rb2610.SHFE
 7   2026-05-15 21:06:00  rb2610.SHFE
 8   2026-05-15 21:07:00  rb2610.SHFE
 9   2026-05-15 21:08:00  rb2610.SHFE
 10  2026-05-15 21:09:00  rb2610.SHFE
 11  2026-05-15 21:10:00  rb2610.SHFE
 12  2026-05-15 21:11:00  rb2610.SHFE
 13  2026-05-15 21:12:00  rb2610.SHFE
 14  2026-05-15 21:13:00  rb2610.SHFE
 15  2026-05-15 21:14:00  rb2610.SHFE
 16  2026-05-15 21:15:00  rb2610.SHFE
 17  2026-05-15 21:16:00  rb2610.SHFE
 18  2026-05-15 21:17:00  rb2610.SHFE
 19  2026-05-15 21:18:00  rb2610.SHFE
 20  2026-05-15 20:59:00  rb2610.SHFE
 21  2026-05-15 21:00:00  rb2610.SHFE
 22  2026-05-15 21:01:00  rb2610.SHFE
 23  2026-05-15 21:02:00  rb2610.SHFE
 24  2026-05-15 21:03:00  rb2610.SHFE
 25  2026-05-15 21:04:00  rb2610.SHFE
 26  2026-05-15 21:05:00  rb2610.SHFE
 27  2026-05-15 21:06:00  rb2610.SHFE
 28  2026-05-15 21:07:00  rb2610.SHFE
 29  2026-05-15 21:08:00  rb2610.SHFE
 30  2026-05-15 21:09:00  rb2610.SHFE
 31  2026-05-15 21:10:00  rb2610.SHFE
 32  2026-05-15 21:11:00  rb2610.SHFE
 33  2026-05-15 21:12:00  rb2610.SHFE
 34  2026-05-15 21:13:00  rb2610.SHFE
 35  2026-05-15 21:14:00  rb2610.SHFE
 36  2026-05-15 21:15:00  rb2610.SHFE
 37  2026-05-15 21:16:00  rb2610.SHFE
 38  2026-05-15 21:17:00  rb2610.SHFE
 39  2026-05-15 21:18:00  rb2610.SHFE  }

In [10]:
cmp = compare_frames(dt1.reset_index(drop=True), dt2.reset_index(drop=True))
cmp

{'shape_equal': True,
 'columns_equal': True,
 'column_summary':            column  equal  mismatch_count
 0       vt_symbol   True               0
 1          symbol   True               0
 2        exchange   True               0
 3            open   True               0
 4            high   True               0
 5             low   True               0
 6           close   True               0
 7            date   True               0
 8            time   True               0
 9        datetime   True               0
 10         volume   True               0
 11          value   True               0
 12  open_interest   True               0
 13           vwap   True               0,
 'diff_rows': Empty DataFrame
 Columns: []
 Index: []}

In [11]:
cmp = compare_frames(dt0.reset_index(drop=True), dt1.reset_index(drop=True))
cmp

{'shape_equal': True,
 'columns_equal': True,
 'column_summary':            column  equal  mismatch_count
 0       vt_symbol   True               0
 1          symbol   True               0
 2        exchange   True               0
 3            open   True               0
 4            high   True               0
 5             low   True               0
 6           close   True               0
 7            date  False             122
 8            time   True               0
 9        datetime  False             122
 10         volume   True               0
 11          value   True               0
 12  open_interest   True               0
 13           vwap   True               0,
 'diff_rows':     row    column                  old                  new  \
 0     0      date           2026-05-15           2026-05-17
 1     1      date           2026-05-15           2026-05-17
 2     2      date           2026-05-15           2026-05-17
 3     3      date           2026-05-15           2026-05-17
 4     4      date           2026-05-15           2026-05-17
 5     5      date           2026-05-15           2026-05-17
 6     6      date           2026-05-15           2026-05-17
 7     7      date           2026-05-15           2026-05-17
 8     8      date           2026-05-15           2026-05-17
 9     9      date           2026-05-15           2026-05-17
 10   10      date           2026-05-15           2026-05-17
 11   11      date           2026-05-15           2026-05-17
 12   12      date           2026-05-15           2026-05-17
 13   13      date           2026-05-15           2026-05-17
 14   14      date           2026-05-15           2026-05-17
 15   15      date           2026-05-15           2026-05-17
 16   16      date           2026-05-15           2026-05-17
 17   17      date           2026-05-15           2026-05-17
 18   18      date           2026-05-15           2026-05-17
 19   19      date           2026-05-15           2026-05-17
 20    0  datetime  2026-05-15 20:59:00  2026-05-17 20:59:00
 21    1  datetime  2026-05-15 21:00:00  2026-05-17 21:00:00
 22    2  datetime  2026-05-15 21:01:00  2026-05-17 21:01:00
 23    3  datetime  2026-05-15 21:02:00  2026-05-17 21:02:00
 24    4  datetime  2026-05-15 21:03:00  2026-05-17 21:03:00
 25    5  datetime  2026-05-15 21:04:00  2026-05-17 21:04:00
 26    6  datetime  2026-05-15 21:05:00  2026-05-17 21:05:00
 27    7  datetime  2026-05-15 21:06:00  2026-05-17 21:06:00
 28    8  datetime  2026-05-15 21:07:00  2026-05-17 21:07:00
 29    9  datetime  2026-05-15 21:08:00  2026-05-17 21:08:00
 30   10  datetime  2026-05-15 21:09:00  2026-05-17 21:09:00
 31   11  datetime  2026-05-15 21:10:00  2026-05-17 21:10:00
 32   12  datetime  2026-05-15 21:11:00  2026-05-17 21:11:00
 33   13  datetime  2026-05-15 21:12:00  2026-05-17 21:12:00
 34   14  datetime  2026-05-15 21:13:00  2026-05-17 21:13:00
 35   15  datetime  2026-05-15 21:14:00  2026-05-17 21:14:00
 36   16  datetime  2026-05-15 21:15:00  2026-05-17 21:15:00
 37   17  datetime  2026-05-15 21:16:00  2026-05-17 21:16:00
 38   18  datetime  2026-05-15 21:17:00  2026-05-17 21:17:00
 39   19  datetime  2026-05-15 21:18:00  2026-05-17 21:18:00

                datetime    vt_symbol
 0   2026-05-15 20:59:00  rb2610.SHFE
 1   2026-05-15 21:00:00  rb2610.SHFE
 2   2026-05-15 21:01:00  rb2610.SHFE
 3   2026-05-15 21:02:00  rb2610.SHFE
 4   2026-05-15 21:03:00  rb2610.SHFE
 5   2026-05-15 21:04:00  rb2610.SHFE
 6   2026-05-15 21:05:00  rb2610.SHFE
 7   2026-05-15 21:06:00  rb2610.SHFE
 8   2026-05-15 21:07:00  rb2610.SHFE
 9   2026-05-15 21:08:00  rb2610.SHFE
 10  2026-05-15 21:09:00  rb2610.SHFE
 11  2026-05-15 21:10:00  rb2610.SHFE
 12  2026-05-15 21:11:00  rb2610.SHFE
 13  2026-05-15 21:12:00  rb2610.SHFE
 14  2026-05-15 21:13:00  rb2610.SHFE
 15  2026-05-15 21:14:00  rb2610.SHFE
 16  2026-05-15 21:15:00  rb2610.SHFE
 17  2026-05-15 21:16:00  rb2610.SHFE
 18  2026-05-15 21:17:00  rb2610.SHFE
 19  2026-05-15 21:18:00  rb2610.SHFE
 20  2026-05-15 20:59:00  rb2610.SHFE
 21  2026-05-15 21:00:00  rb2610.SHFE
 22  2026-05-15 21:01:00  rb2610.SHFE
 23  2026-05-15 21:02:00  rb2610.SHFE
 24  2026-05-15 21:03:00  rb2610.SHFE
 25  2026-05-15 21:04:00  rb2610.SHFE
 26  2026-05-15 21:05:00  rb2610.SHFE
 27  2026-05-15 21:06:00  rb2610.SHFE
 28  2026-05-15 21:07:00  rb2610.SHFE
 29  2026-05-15 21:08:00  rb2610.SHFE
 30  2026-05-15 21:09:00  rb2610.SHFE
 31  2026-05-15 21:10:00  rb2610.SHFE
 32  2026-05-15 21:11:00  rb2610.SHFE
 33  2026-05-15 21:12:00  rb2610.SHFE
 34  2026-05-15 21:13:00  rb2610.SHFE
 35  2026-05-15 21:14:00  rb2610.SHFE
 36  2026-05-15 21:15:00  rb2610.SHFE
 37  2026-05-15 21:16:00  rb2610.SHFE
 38  2026-05-15 21:17:00  rb2610.SHFE
 39  2026-05-15 21:18:00  rb2610.SHFE  }

In [15]:
dt0

,vt_symbol,symbol,exchange,open,high,low,close,date,time,datetime,volume,value,open_interest,vwap
229,rb2610.SHFE,rb2610,SHFE,3218.0,3218.0,3218.0,3218.0,2026-05-25,20:59:00,2026-05-25 20:59:00,0.0,0.000000e+00,1793318.0,3218.000000
230,rb2610.SHFE,rb2610,SHFE,3217.0,3217.0,3204.0,3205.0,2026-05-25,21:00:00,2026-05-25 21:00:00,41476.0,1.331469e+09,1787507.0,3210.216004
231,rb2610.SHFE,rb2610,SHFE,3204.0,3207.0,3197.0,3198.0,2026-05-25,21:01:00,2026-05-25 21:01:00,32152.0,1.029599e+09,1784493.0,3202.287136
232,rb2610.SHFE,rb2610,SHFE,3197.0,3201.0,3193.0,3200.0,2026-05-25,21:02:00,2026-05-25 21:02:00,26315.0,8.411869e+08,1783985.0,3196.605966
233,rb2610.SHFE,rb2610,SHFE,3199.0,3199.0,3194.0,3196.0,2026-05-25,21:03:00,2026-05-25 21:03:00,16344.0,5.223600e+08,1784734.0,3196.035365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,rb2610.SHFE,rb2610,SHFE,3146.0,3148.0,3146.0,3148.0,2026-05-26,14:57:00,2026-05-26 14:57:00,8124.0,2.556354e+08,1735090.0,3146.668636
225,rb2610.SHFE,rb2610,SHFE,3148.0,3148.0,3146.0,3147.0,2026-05-26,14:58:00,2026-05-26 14:58:00,7289.0,2.293757e+08,1733994.0,3146.875154
226,rb2610.SHFE,rb2610,SHFE,3146.0,3147.0,3145.0,3146.0,2026-05-26,14:59:00,2026-05-26 14:59:00,7937.0,2.497108e+08,1733218.0,3146.160766
227,rb2610.SHFE,rb2610,SHFE,3146.0,3146.0,3146.0,3146.0,2026-05-26,15:00:00,2026-05-26 15:00:00,6.0,1.887600e+05,1733217.0,3146.000000
228,rb2610.SHFE,rb2610,SHFE,3146.0,3146.0,3146.0,3146.0,2026-05-26,15:14:00,2026-05-26 15:14:00,0.0,0.000000e+00,1733217.0,3146.000000