In [1]:
import datetime
from dotenv import load_dotenv

load_dotenv()

True

In [2]:
from lib.attr001.ftd001 import *

/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:11: UserWarning: if use distributed calculating, please configure MQ_URL
  warnings.warn('if use distributed calculating, please configure MQ_URL')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:15: UserWarning: if use distributed calculating, please configure NTN_URL
  warnings.warn('if use distributed calculating, please configure NTN_URL')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:19: UserWarning: if use memory database, please configure KN_MG
  warnings.warn('if use memory database, please configure KN_MG')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:27: UserWarning: if use trader, please configure ATL_URL
  warnings.warn('if use trader, please configure ATL_URL')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:31: UserWarning: if use trader, please configure IREY_URL
  warnings.warn('if use trader, please configure IREY_URL')

In [14]:
instruments = 'rbb'
begin_time = datetime.datetime(2024, 1, 20)
end_time = datetime.datetime(2024, 3, 1)

In [15]:
bench_data = fetch_bench_data(instruments, begin_time, end_time, adjusted_method=None)

_cumfactor is not fut_algin_factors column

In [16]:
research_data = fetch_research_data(instruments, begin_time, end_time, adjusted_method=None)

In [17]:
bench_data = bench_data.unstack()
research_data = research_data.unstack()

research_data1 = research_data.shift(1)

In [18]:
from lumina.impulse.i005.core.fz002 import fz002

In [22]:
bench_factors = fz002(close=bench_data['close'], volume=bench_data['volume'], quant=0.02,
      window=1, weriod=2, ewm=True)

In [24]:
bench_factors.loc['2024-02-21 09:50:00':]

code                       RB
trade_time
2024-02-21 09:50:00  0.000097
2024-02-21 09:51:00  0.000469
2024-02-21 09:52:00  0.000156
2024-02-21 09:53:00  0.000052
2024-02-21 09:54:00  0.000017
...                       ...
2024-03-01 22:56:00  0.000543
2024-03-01 22:57:00  0.000181
2024-03-01 22:58:00  0.000060
2024-03-01 22:59:00  0.000156
2024-03-01 23:00:00  0.000190

[2719 rows x 1 columns]

In [25]:
research_factors = fz002(close=research_data['close'], volume=research_data['volume'], quant=0.02,
      window=1, weriod=2, ewm=True)#.tail()

In [26]:
research_factors.loc['2024-02-21 09:50:00':]

code                       RB
trade_time
2024-02-21 09:50:00  0.000338
2024-02-21 09:51:00  0.000113
2024-02-21 09:52:00  0.000038
2024-02-21 09:53:00  0.000013
2024-02-21 09:54:00 -0.000095
...                       ...
2024-03-01 14:57:00  0.000214
2024-03-01 14:58:00  0.000071
2024-03-01 14:59:00  0.000024
2024-03-01 15:00:00  0.000008
2024-03-01 15:19:00  0.000003

[2628 rows x 1 columns]

In [27]:
research_factors1 = fz002(close=research_data1['close'], volume=research_data1['volume'], quant=0.02,
      window=1, weriod=2, ewm=True)

In [28]:
research_factors1.loc['2024-02-21 09:50:00':]

code                       RB
trade_time
2024-02-21 09:50:00  0.000141
2024-02-21 09:51:00  0.000338
2024-02-21 09:52:00  0.000113
2024-02-21 09:53:00  0.000038
2024-02-21 09:54:00  0.000013
...                       ...
2024-03-01 14:57:00 -0.000023
2024-03-01 14:58:00  0.000214
2024-03-01 14:59:00  0.000071
2024-03-01 15:00:00  0.000024
2024-03-01 15:19:00  0.000008

[2628 rows x 1 columns]

In [29]:
#research_data.shift(1)['volume'].loc['2026-05-26 14:36:00':'2026-05-27 15:00:00']

In [30]:
#bench_data['volume'].loc['2026-05-26 14:36:00':'2026-05-27 15:00:00']